# Build directories — ONE scheme: build/<variant>-<config>, everything under build/.
# variant = frontend or target platform (sdl / gui / win / mac / rpm / deb / flatpak),
# config  = debug or release. build/ itself is the canonical dev tree (./build/jnext
# + the test binaries); `make unit-test-clean` removes it and everything below it.
BUILD_DIR_SDL_DEBUG   := build/sdl-debug
BUILD_DIR_SDL_RELEASE := build/sdl-release
BUILD_DIR_GUI_DEBUG   := build/gui-debug
BUILD_DIR_GUI_RELEASE := build/gui-release
BUILD_DIR_WIN_RELEASE := build/win-release
BUILD_DIR_WIN_SDL_RELEASE := build/win-sdl-release
BUILD_DIR_WIN_QT5_RELEASE := build/win-qt5-release
BUILD_DIR_QT5_CHECK   := build/qt5-check
BUILD_DIR_WIN32_SDL_RELEASE := build/win32-sdl-release
BUILD_DIR_WIN32_QT5_RELEASE := build/win32-qt5-release
BUILD_DIR_MAC_RELEASE := build/mac-release
BUILD_DIR_RPM_RELEASE := build/rpm-release
BUILD_DIR_DEB_RELEASE := build/deb-release
BUILD_DIR_FPK_RELEASE := build/flatpak-release
CMAKE             := cmake
JOBS              := $(shell nproc 2>/dev/null || sysctl -n hw.logicalcpu 2>/dev/null || echo 4)
CC                := /usr/bin/gcc
CXX               := /usr/bin/g++

# Pin windres to the SAME absolute path fedora's mingw toolchain file uses.
# Without the pin, CMake's own RC detection resolves windres through PATH —
# /usr/sbin/... under a sbin-first PATH (GitHub job containers) — while later
# re-reads of the toolchain file plant /usr/bin/... in the top-level scope
# (its `IF(NOT $ENV{RC})` guard mis-fires once CMake exports RC after RC
# detection). enable_language(RC) then sees cache != scope and CMake WIPES the
# whole cache mid-configure — toolchain file included — and re-configures
# natively, dying at find_package(ZLIB) (GH #108 CI failure, run 30200486697).
MINGW64_RC        := -DCMAKE_RC_COMPILER=/usr/bin/x86_64-w64-mingw32-windres
MINGW32_RC        := -DCMAKE_RC_COMPILER=/usr/bin/i686-w64-mingw32-windres

# Documentation single source (see `make docs-man`). doc/man/jnext.1.md generates
# BOTH outputs below, and both are committed: building jnext from source never
# needs pandoc, only editing the docs does.
GUIDE_PORT        ?= 8000
# mkdocs stamps sitemap.xml.gz with the BUILD DATE, so an unchanged guide
# rendered tomorrow differs from today's — which would have failed docs-check,
# and therefore every unit-test and regression run, from the day after any
# render. Pinning SOURCE_DATE_EPOCH (reproducible-builds convention) removes
# the clock from the output entirely. The value is arbitrary and fixed; the
# sitemap carries no content (no site_url is set, so it is an empty urlset).
GUIDE_BUILD_ENV   := SOURCE_DATE_EPOCH=1700000000
# Renderer fingerprint: VERSIONS ONLY. `mkdocs --version` also prints the
# install path, which differs per machine and would make every other host
# look like a version mismatch.
GUIDE_FINGERPRINT := python3 -c "import importlib.metadata as m; print('mkdocs', m.version('mkdocs')); print('mkdocs-material', m.version('mkdocs-material'))"
GUIDE_RENDERER    := src/doc/user-guide-renderer.txt
GUIDE_SRC         := src/doc/user-guide
GUIDE_OUT         := doc/user-guide
# Same fingerprint idea as the guide: pandoc emits byte-different roff/gfm
# across versions, so a diff against outputs generated by a different pandoc
# reports a VERSION GAP as staleness. That is precisely what broke CI when it
# ran Ubuntu's pandoc 3.1.3 against outputs made with 3.7.0.2 — with no hint
# in the message that the version, not an edit, was the cause.
MAN_FINGERPRINT   := pandoc --version | head -1
MAN_RENDERER      := doc/man/pandoc-version.txt
MAN_SRC           := doc/man/jnext.1.md
MAN_OUT           := doc/man/jnext.1
USAGE_OUT         := USAGE.md

# Every recipe runs in the C locale. Two reasons, both about not lying:
#  - builds: compiler/linker diagnostics stay in English (greppable, quotable).
#  - tests:  a test's verdict must depend on the code, not on the user's LANG.
#    Qt's QApplication calls setlocale(LC_ALL, "") on construction, which localises
#    strerror() — screenshot-io-qt-func greps for "No such file or directory" and
#    duly FAILed on a Spanish desktop while its headless twin (no QApplication)
#    passed. LC_ALL overrides LANG, so this holds regardless of the caller's env.
export LC_ALL := C

# ANSI color palette (matches user prompt theme: 256-color mode)
RESET     := \033[0m
BOLD      := \033[1m
CYAN      := \033[36m
FG_BLACK  := \033[38;5;0m
FG_WHITE  := \033[38;5;15m
BG_PASS   := \033[48;5;42m
BG_SKIP   := \033[48;5;220m
BG_FAIL   := \033[48;5;161m
BADGE_PASS := $(FG_BLACK)$(BG_PASS)
BADGE_SKIP := $(FG_BLACK)$(BG_SKIP)
BADGE_FAIL := $(FG_WHITE)$(BG_FAIL)

.PHONY: default sdl-debug sdl-release clean sdl-debug-clean sdl-release-clean sdl-debug-run sdl-release-run \
       gui-debug gui-release gui-debug-clean gui-release-clean gui-debug-run gui-release-run gui-clean \
       unit-test-clean unit-test-build \
       kloc-count regression unit-test lint-assertions lint-makefile-help harness-selftest traceability-selftest traceability-accounting-check worktree-bootstrap bench \
       docs-man docs-check docs-man-check docs-userguide-check docs-userguide read-userguide cli-check \
       bump bump-patch bump-minor bump-major version publish-release \
       package-src package-rpm package-deb package-flatpak package-win package-macos win-release package-test \
       win-sdl-release package-win-sdl win32-sdl-release package-win32-sdl \
       win-qt5-release package-win-qt5 win32-qt5-release package-win32-qt5 qt5-guard-build \
       package-contract-test packaging-selftest verify-macos-dmg
.SILENT:

# Show this help message with descriptions for all targets
default:
	printf "\n$(BOLD)Available targets:$(RESET)\n\n"
	awk 'BEGIN {FS = ":.*?"} /^# / {helpMessage = substr($$0, 3); next} /^[a-zA-Z0-9_-]+:/ {if (helpMessage) {printf "  $(CYAN)$(BOLD)%-34s$(RESET)$(RESET) %s\n", $$1, helpMessage}; helpMessage = ""}' $(MAKEFILE_LIST)
	printf "\n"

# Configure and build the SDL-only frontend in Debug mode (sanitizers + debug symbols)
sdl-debug:
	$(CMAKE) -B $(BUILD_DIR_SDL_DEBUG) \
		-DCMAKE_BUILD_TYPE=Debug \
		-DCMAKE_C_COMPILER=$(CC) \
		-DCMAKE_CXX_COMPILER=$(CXX) \
		-DCMAKE_CXX_FLAGS="-g -fno-omit-frame-pointer" \
		-DENABLE_TESTS=ON
	$(CMAKE) --build $(BUILD_DIR_SDL_DEBUG) -j$(JOBS)

# Run the emulator (SDL-only debug build)
sdl-debug-run: sdl-debug
	$(BUILD_DIR_SDL_DEBUG)/jnext

# Remove the SDL-only debug build directory
sdl-debug-clean:
	rm -rf $(BUILD_DIR_SDL_DEBUG)

# Configure and build the SDL-only frontend in Release mode (optimized, no sanitizers)
sdl-release:
	$(CMAKE) -B $(BUILD_DIR_SDL_RELEASE) \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_C_COMPILER=$(CC) \
		-DCMAKE_CXX_COMPILER=$(CXX) \
		-DCMAKE_CXX_FLAGS="-O2 -DNDEBUG" \
		-DENABLE_TESTS=OFF
	$(CMAKE) --build $(BUILD_DIR_SDL_RELEASE) -j$(JOBS)

# Run the emulator (SDL-only release build)
sdl-release-run: sdl-release
	$(BUILD_DIR_SDL_RELEASE)/jnext

# Remove the SDL-only release build directory
sdl-release-clean:
	rm -rf $(BUILD_DIR_SDL_RELEASE)

# Configure and build Qt GUI in Debug mode
gui-debug:
	$(CMAKE) -B $(BUILD_DIR_GUI_DEBUG) \
		-DCMAKE_BUILD_TYPE=Debug \
		-DCMAKE_C_COMPILER=$(CC) \
		-DCMAKE_CXX_COMPILER=$(CXX) \
		-DCMAKE_CXX_FLAGS="-Og -g -fno-omit-frame-pointer" \
		-DENABLE_QT_UI=ON \
		-DENABLE_TESTS=ON
	$(CMAKE) --build $(BUILD_DIR_GUI_DEBUG) -j$(JOBS)

# Run the emulator with Qt GUI (debug build)
gui-debug-run: gui-debug
	$(BUILD_DIR_GUI_DEBUG)/jnext

# Remove GUI debug build directory
gui-debug-clean:
	rm -rf $(BUILD_DIR_GUI_DEBUG)

# Configure and build Qt GUI in Release mode
gui-release:
	$(CMAKE) -B $(BUILD_DIR_GUI_RELEASE) \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_C_COMPILER=$(CC) \
		-DCMAKE_CXX_COMPILER=$(CXX) \
		-DCMAKE_CXX_FLAGS="-O2 -DNDEBUG" \
		-DENABLE_QT_UI=ON \
		-DENABLE_TESTS=OFF
	$(CMAKE) --build $(BUILD_DIR_GUI_RELEASE) -j$(JOBS)

# Cross-compile ONLY the Windows jnext.exe (Fedora MinGW; no packaging)
win-release:
	@# mingw64-cmake ships in mingw64-filesystem and may be present without the
	@# actual cross toolchain/libraries. Check the cross gcc and mingw Qt6 too,
	@# so a missing package is a clear "install these" message, not a cryptic
	@# "compiler not found" from deep inside CMake's project() call.
	@if ! command -v mingw64-cmake >/dev/null 2>&1 \
	   || ! command -v x86_64-w64-mingw32-gcc >/dev/null 2>&1 \
	   || [ ! -f /usr/x86_64-w64-mingw32/sys-root/mingw/lib/cmake/Qt6/Qt6Config.cmake ]; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) Fedora MinGW cross toolchain/libraries incomplete.\n"; \
		printf "  Install them all:\n"; \
		printf "  $(BOLD)sudo dnf install mingw64-gcc mingw64-gcc-c++ mingw64-qt6-qtbase \\\\\n"; \
		printf "    mingw64-sdl2-compat mingw64-zlib \\\\\n"; \
		printf "    mingw64-libpng mingw64-winpthreads$(RESET)\n"; \
		printf "  (mingw64-filesystem supplies mingw64-cmake; native qt6-qtbase-devel supplies moc/rcc/uic.)\n"; \
		exit 1; \
	fi
	mingw64-cmake -S . -B $(BUILD_DIR_WIN_RELEASE) $(MINGW64_RC) -DENABLE_QT_UI=ON -DENABLE_TESTS=OFF
	$(CMAKE) --build $(BUILD_DIR_WIN_RELEASE) -j$(JOBS)
	@# Bundle the Qt6/SDL2 runtime DLLs + Qt plugins next to the exe so it runs
	@# in place (jnext.exe alone can't start — missing Qt6Core.dll and, even with
	@# the DLLs, the platforms/qwindows.dll plugin).
	bash packaging/windows/bundle-dlls.sh $(BUILD_DIR_WIN_RELEASE)/jnext.exe $(BUILD_DIR_WIN_RELEASE)
	@printf "$(BOLD)Windows executable (+ bundled DLLs):$(RESET) $(BUILD_DIR_WIN_RELEASE)/jnext.exe\n"

# Cross-compile the SDL-only Windows jnext.exe (no Qt — Windows 8+ compatible; GH #108)
win-sdl-release:
	@# Same toolchain check as win-release, minus the Qt6 requirement — the
	@# SDL-only build (ENABLE_QT_UI=OFF) is exactly the Win7/8-era leg where
	@# fedora's mingw Qt6 (hard Windows 10 floor) is unusable. See
	@# doc/design/WINDOWS-COMPAT-PLAN.md for the audited floors.
	@if ! command -v mingw64-cmake >/dev/null 2>&1 \
	   || ! command -v x86_64-w64-mingw32-gcc >/dev/null 2>&1; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) Fedora MinGW cross toolchain incomplete.\n"; \
		printf "  Install it:\n"; \
		printf "  $(BOLD)sudo dnf install mingw64-gcc mingw64-gcc-c++ mingw64-sdl2-compat \\\\\n"; \
		printf "    mingw64-zlib mingw64-libpng mingw64-winpthreads$(RESET)\n"; \
		printf "  (mingw64-filesystem supplies mingw64-cmake.)\n"; \
		exit 1; \
	fi
	@# ENABLE_DEBUGGER=OFF is load-bearing: it defaults ON and src/debugger
	@# does find_package(Qt6 REQUIRED) at configure time, which would make the
	@# "Qt6 not needed" toolchain guard above a lie on a Qt-less host. The
	@# shipped exe is identical either way (the debugger ifdefs live only in
	@# src/gui, which the SDL build never compiles).
	mingw64-cmake -S . -B $(BUILD_DIR_WIN_SDL_RELEASE) $(MINGW64_RC) -DENABLE_QT_UI=OFF -DENABLE_DEBUGGER=OFF -DENABLE_TESTS=OFF
	$(CMAKE) --build $(BUILD_DIR_WIN_SDL_RELEASE) -j$(JOBS)
	bash packaging/windows/bundle-dlls.sh $(BUILD_DIR_WIN_SDL_RELEASE)/jnext.exe $(BUILD_DIR_WIN_SDL_RELEASE)
	@printf "$(BOLD)Windows SDL-only executable (+ bundled DLLs):$(RESET) $(BUILD_DIR_WIN_SDL_RELEASE)/jnext.exe\n"

# Cross-compile the Qt5 full-GUI Windows jnext.exe (Win7/8 legacy leg; GH #108 Phase A)
win-qt5-release:
	@# Toolchain guard: mingw Qt5 runtime+devel (Qt5Config.cmake) AND the cross
	@# host tools (moc) from mingw64-qt5-qmake — AUTOMOC needs them.
	@if ! command -v mingw64-cmake >/dev/null 2>&1 \
	   || ! command -v x86_64-w64-mingw32-gcc >/dev/null 2>&1 \
	   || [ ! -f /usr/x86_64-w64-mingw32/sys-root/mingw/lib/cmake/Qt5/Qt5Config.cmake ] \
	   || ! command -v x86_64-w64-mingw32-moc-qt5 >/dev/null 2>&1; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) Fedora MinGW Qt5 cross toolchain incomplete.\n"; \
		printf "  Install it:\n"; \
		printf "  $(BOLD)sudo dnf install mingw64-gcc mingw64-gcc-c++ mingw64-qt5-qtbase \\\\\n"; \
		printf "    mingw64-qt5-qtbase-devel mingw64-qt5-qmake mingw64-sdl2-compat \\\\\n"; \
		printf "    mingw64-zlib mingw64-libpng mingw64-winpthreads$(RESET)\n"; \
		printf "  (mingw64-filesystem supplies mingw64-cmake.)\n"; \
		exit 1; \
	fi
	mingw64-cmake -S . -B $(BUILD_DIR_WIN_QT5_RELEASE) $(MINGW64_RC) -DENABLE_QT_UI=ON -DENABLE_DEBUGGER=ON -DJNEXT_FORCE_QT5=ON -DENABLE_TESTS=OFF
	$(CMAKE) --build $(BUILD_DIR_WIN_QT5_RELEASE) -j$(JOBS)
	bash packaging/windows/bundle-dlls.sh $(BUILD_DIR_WIN_QT5_RELEASE)/jnext.exe $(BUILD_DIR_WIN_QT5_RELEASE)
	@printf "$(BOLD)Windows Qt5 full-GUI executable (+ bundled DLLs):$(RESET) $(BUILD_DIR_WIN_QT5_RELEASE)/jnext.exe\n"

# Build Linux jnext against Qt5 (JNEXT_FORCE_QT5) — dual-maintenance compile guard (GH #108)
qt5-guard-build:
	$(CMAKE) -B $(BUILD_DIR_QT5_CHECK) \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_C_COMPILER=$(CC) \
		-DCMAKE_CXX_COMPILER=$(CXX) \
		-DCMAKE_CXX_FLAGS="-O2 -DNDEBUG" \
		-DENABLE_QT_UI=ON \
		-DENABLE_DEBUGGER=ON \
		-DJNEXT_FORCE_QT5=ON \
		-DENABLE_TESTS=OFF
	$(CMAKE) --build $(BUILD_DIR_QT5_CHECK) -j$(JOBS)
	$(BUILD_DIR_QT5_CHECK)/jnext --version

# Cross-compile the SDL-only 32-bit (i686) Windows jnext.exe — repo-internal (GH #108 Phase C)
win32-sdl-release:
	@# i686 twin of win-sdl-release: mingw32-cmake + the mingw32-* library set.
	@# SDL-only is the meaningful 32-bit leg today — fedora's mingw32 Qt6 would
	@# carry the same Windows 10 floor as the x64 Qt package, defeating the
	@# point of a 32-bit build (doc/design/WINDOWS-COMPAT-PLAN.md §4/§7).
	@if ! command -v mingw32-cmake >/dev/null 2>&1 \
	   || ! command -v i686-w64-mingw32-gcc >/dev/null 2>&1; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) Fedora MinGW i686 cross toolchain incomplete.\n"; \
		printf "  Install it:\n"; \
		printf "  $(BOLD)sudo dnf install mingw32-gcc mingw32-gcc-c++ mingw32-sdl2-compat \\\\\n"; \
		printf "    mingw32-zlib mingw32-libpng mingw32-winpthreads$(RESET)\n"; \
		printf "  (mingw32-filesystem supplies mingw32-cmake.)\n"; \
		exit 1; \
	fi
	@# ENABLE_DEBUGGER=OFF is load-bearing for the same reason as in
	@# win-sdl-release: it defaults ON and src/debugger does
	@# find_package(Qt6 REQUIRED) at configure time.
	mingw32-cmake -S . -B $(BUILD_DIR_WIN32_SDL_RELEASE) $(MINGW32_RC) -DENABLE_QT_UI=OFF -DENABLE_DEBUGGER=OFF -DENABLE_TESTS=OFF
	$(CMAKE) --build $(BUILD_DIR_WIN32_SDL_RELEASE) -j$(JOBS)
	@# bundle-dlls.sh reads the exe's PE machine field and resolves DLLs from
	@# the i686 sysroot automatically.
	bash packaging/windows/bundle-dlls.sh $(BUILD_DIR_WIN32_SDL_RELEASE)/jnext.exe $(BUILD_DIR_WIN32_SDL_RELEASE)
	@printf "$(BOLD)Windows 32-bit SDL-only executable (+ bundled DLLs):$(RESET) $(BUILD_DIR_WIN32_SDL_RELEASE)/jnext.exe\n"

# Cross-compile the Qt5 full-GUI 32-bit (i686) Windows jnext.exe (Win7 32-bit leg; GH #108 Phase C)
win32-qt5-release:
	@# i686 twin of win-qt5-release: mingw32-cmake + the mingw32 Qt5 stack.
	@# Guard mirrors win-qt5-release — Qt5 runtime+devel (Qt5Config.cmake in
	@# the i686 sysroot) AND the cross host tools (i686-w64-mingw32-moc-qt5
	@# from mingw32-qt5-qmake — AUTOMOC needs them).
	@if ! command -v mingw32-cmake >/dev/null 2>&1 \
	   || ! command -v i686-w64-mingw32-gcc >/dev/null 2>&1 \
	   || [ ! -f /usr/i686-w64-mingw32/sys-root/mingw/lib/cmake/Qt5/Qt5Config.cmake ] \
	   || ! command -v i686-w64-mingw32-moc-qt5 >/dev/null 2>&1; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) Fedora MinGW i686 Qt5 cross toolchain incomplete.\n"; \
		printf "  Install it:\n"; \
		printf "  $(BOLD)sudo dnf install mingw32-gcc mingw32-gcc-c++ mingw32-qt5-qtbase \\\\\n"; \
		printf "    mingw32-qt5-qtbase-devel mingw32-qt5-qmake mingw32-sdl2-compat \\\\\n"; \
		printf "    mingw32-zlib mingw32-libpng mingw32-winpthreads$(RESET)\n"; \
		printf "  (mingw32-filesystem supplies mingw32-cmake.)\n"; \
		exit 1; \
	fi
	mingw32-cmake -S . -B $(BUILD_DIR_WIN32_QT5_RELEASE) $(MINGW32_RC) -DENABLE_QT_UI=ON -DENABLE_DEBUGGER=ON -DJNEXT_FORCE_QT5=ON -DENABLE_TESTS=OFF
	$(CMAKE) --build $(BUILD_DIR_WIN32_QT5_RELEASE) -j$(JOBS)
	@# bundle-dlls.sh reads the exe's PE machine field (i686 sysroot) and the
	@# qt5core.dll import (Qt5 plugin root) — no flags needed for either.
	bash packaging/windows/bundle-dlls.sh $(BUILD_DIR_WIN32_QT5_RELEASE)/jnext.exe $(BUILD_DIR_WIN32_QT5_RELEASE)
	@printf "$(BOLD)Windows 32-bit Qt5 full-GUI executable (+ bundled DLLs):$(RESET) $(BUILD_DIR_WIN32_QT5_RELEASE)/jnext.exe\n"

# Run the emulator with Qt GUI (release build)
gui-release-run: gui-release
	$(BUILD_DIR_GUI_RELEASE)/jnext

# Remove GUI release build directory
gui-release-clean:
	rm -rf $(BUILD_DIR_GUI_RELEASE)

# Remove all GUI build directories
gui-clean: gui-debug-clean gui-release-clean

# Remove all build directories (sdl/gui + unit-test; build/ takes the rest with it)
clean: sdl-debug-clean sdl-release-clean gui-clean unit-test-clean

# Run the full regression test suite (screenshot + functional tests)
regression: lint-makefile-help unit-test-build gui-release sdl-release docs-check cli-check
	@# Depends on unit-test-build: regression.sh runs build/test/rewind_test, and a
	@# `make clean` deletes it. It used to vanish from the suite with no row printed.
	@# gui-release is a REAL prerequisite, not a convenience: regression.sh runs
	@# build/gui-release/jnext, so without it the suite silently tests whatever
	@# binary happens to be lying there. A stale one gives false FAILs (the binary
	@# lacks a fix the test expects) and, worse, false PASSes (it lacks the bug the
	@# test would have caught). Building it here makes "the tests ran against this
	@# source" true by construction instead of by discipline — 2026-07-19, after a
	@# 14-hour-old binary produced two bogus FAILs immediately before a version bump.
	@# sdl-release is the SAME contract for a SECOND binary (GH #122): SdlApp runs
	@# only when ENABLE_QT_UI=OFF, so gui-release compiles the SDL frontend but never
	@# executes it, and sdl-keypress-func is the one row that does. `make clean`
	@# deletes it (clean depends on sdl-release-clean), hence building it here.
	bash test/00regression/regression.sh

# Fail if a declared unit-test suite is neither traced nor tombstoned in the matrix
traceability-accounting-check:
	@# doc/testing/TRACEABILITY-MATRIX.md records what each test row proves and
	@# against what VHDL authority, and WHICH suites it covers used to be a
	@# hand-written table inside the refresh script. That table drifted: it traced
	@# 28 suites for the whole v0.98 series while test/unit-tests.conf grew 49 ->
	@# 80, so ~31 suites were added and traced nowhere. Each addition arrived as
	@# one more name on a warning line that already listed fifty, inside a report
	@# only a human running the version-bump checklist ever saw.
	@#
	@# So the manifest drives it now, and the check runs HERE, on every unit-test
	@# run, exactly like docs-check and cli-check. It costs 0.01 s: no test binary
	@# is run, no test source is read, the matrix is neither opened nor written —
	@# which is why it needs no build prerequisite and can sit ahead of everything
	@# expensive.
	@#
	@# It is NOT the full refresh. That one still exits 1 on the 821-row
	@# `unrecorded` backlog and needs a built test tree; this is the suite-level
	@# gate only, and its exit code (2) is distinct from both that backlog (1) and
	@# an internal error (3).
	@perl test/refresh-traceability-matrix.pl --check-accounting

# Run all subsystem unit tests in parallel (exactly those in test/unit-tests.conf)
unit-test: lint-assertions lint-makefile-help traceability-accounting-check unit-test-build docs-check package-contract-test
	@# lint-makefile-help sits beside lint-assertions for the same reason and at the
	@# same cost (~8 ms of awk over one file, no compiler, no build directory): it is
	@# a structural gate that must fail before anything expensive starts. GH #140 —
	@# eight targets, `regression` and `unit-test` among them, advertised a sentence
	@# fragment in `make` for as long as nobody re-read the listing. Fixing the eight
	@# does not stop the ninth; the rule does.
	@# lint-assertions is a prerequisite for the same reason as docs-check, and it is
	@# FIRST because it is the cheapest gate here (~40 ms of ripgrep over test/ source
	@# text — no compiler, no SD image, no display), so it fails before the build even
	@# starts. Until GH #129 it was reachable ONLY through the regression preflight,
	@# which an author iterating on `make unit-test` never runs: a check(..., true) row
	@# passed its author, passed an independent reviewer, and turned CI red only after
	@# landing on main, from where three more branches inherited it. A gate nobody's
	@# inner loop reaches is not a gate.
	@# It cannot be a row in test/unit-tests.conf: that manifest is cross-checked
	@# against CMake's add_test() registry in BOTH directions, so a non-CMake entry
	@# makes run-unit-tests.sh REFUSE to run ("NOT registered by CMake"). A make
	@# prerequisite leaves the harness's refusal semantics untouched.
	@# The regression suite keeps its OWN copy (scripts/00-preflight-lint.sh, row 1 of
	@# the suite) — same as docs-check sits in both entry points. Do not "de-duplicate"
	@# by deleting either one.
	@# docs-check is a prerequisite, not a courtesy: the man page, USAGE.md and the
	@# rendered user guide are all GENERATED and COMMITTED, so a stale committed
	@# output is a silent lie that no other gate can see. Running it with every test
	@# run makes "the docs match their source" true by construction, not by discipline.
	@# It skips (never fails) where the tool is absent — pandoc for the man half,
	@# mkdocs for the guide half — and hard-fails in CI where both are guaranteed.
	@# NOTE: this proves the generated outputs match their sources. That jnext.1.md
	@# also matches the CLI src/main.cpp parses is proven separately, by cli_options_test
	@# (run below as a declared suite, and as `make cli-check`) — issue #43.
	@# package-contract-test is a prerequisite for the same reason (issue #61): the
	@# packaging scripts are hand-written, ship user-visible artifacts, and had no
	@# automatic gate at all — `make package-test` was called by no workflow and by
	@# no target, which is how its sync-version row stayed red for 46 tags (#60).
	@# Only the HERMETIC half runs here: six bash contract suites on throwaway fake
	@# roots, ~4 s, no compiler and no packaging toolchain. The half that actually
	@# builds rpm/deb/win packages (~4 min) stays in `make package-test`, run as its
	@# own parallel job in ci.yml.
	@bash test/run-unit-tests.sh build
	@# Loud, non-fatal drift guard: the dashboard only refreshes on the explicit
	@# 'unit-test-dashboard' target, so it silently rots. This warns (never fails —
	@# a stale doc must not break the parallel-worktree test flow) when regenerating
	@# from test/unit-tests.conf + the live summary would change the committed dashboard
	@# (stale-counts) OR a live suite is not declared in test/unit-tests.conf (no-row).
	@# Both the generator and this guard key off test/unit-tests.conf. Fix: make unit-test-dashboard.
	@if [ -s build/test-summary.tsv ] && [ -f test/SUBSYSTEM-TESTS-STATUS.md ]; then \
		tmp=$$(mktemp); cp test/SUBSYSTEM-TESTS-STATUS.md $$tmp; \
		bash test/refresh-subsystem-status.sh build/test-summary.tsv $$tmp >/dev/null 2>&1 || true; \
		drift=""; \
		diff -q $$tmp test/SUBSYSTEM-TESTS-STATUS.md >/dev/null 2>&1 || drift="stale-counts"; \
		miss=$$(cut -f1 build/test-summary.tsv | while read b; do grep -qE "^[?]?$$b[[:space:]]" test/unit-tests.conf || echo $$b; done | tr '\n' ' '); \
		[ -n "$$miss" ] && drift="$$drift no-row:[$$miss]"; \
		if [ -n "$$drift" ]; then \
			printf "\n$(BADGE_SKIP) DASHBOARD STALE $(RESET) $$drift\n"; \
			printf "  test/SUBSYSTEM-TESTS-STATUS.md is out of date — run '$(BOLD)make unit-test-dashboard$(RESET)' and commit.\n\n"; \
		fi; \
		rm -f $$tmp; \
	fi

# Build every ENABLE_QT_UI x ENABLE_DEBUGGER combination; fails if any breaks
build-matrix:
	@bash test/build-matrix.sh

# Fail if any target's `make` help description would be discarded (GH #140)
lint-makefile-help:
	@# The help awk keeps only the LAST `# ` line before a target, so a rationale
	@# block below a description silently replaces it. This enforces the project's
	@# documented rule — one `# ` line above a target, rationale inside the recipe
	@# as `@#` lines — structurally, on discarded content rather than on prose.
	@bash test/lint-makefile-help.sh

# Fail if a NEW tautological assertion appeared in test/ (baseline-relative)
lint-assertions:
	@# A missing ripgrep is a hard FAILURE here, not a docs-check-style SKIP. pandoc and
	@# mkdocs are genuinely optional (a source build ships the generated docs committed);
	@# rg is already a hard requirement of `make regression`, whose preflight row FAILs
	@# without it. Skipping would also defeat the point: a lint that does not run reads
	@# as a pass, which is the whole shape of GH #129.
	@bash test/lint-assertions.sh

# Self-test the unit-test harness: inject each fault, assert it refuses to run
harness-selftest: unit-test-build gui-release sdl-release
	@# All three binary prerequisites are load-bearing, and are the same set
	@# `regression` declares: HS-21..24/31/32 drive the regression preflight, which
	@# refuses to run without the jnext binary it resolves (gui-release),
	@# build/test/rewind_test (unit-test-build) and build/sdl-release/jnext
	@# (sdl-release). Declaring none of them left the target that exists to prove
	@# the harness reports faults correctly failing those 6 rows in any fresh
	@# worktree, for reasons unrelated to any injected fault (GH #135).
	@# docs-check and cli-check are deliberately NOT mirrored from `regression`:
	@# they gate the generated docs and the CLI table, neither of which this
	@# self-test reads. No workflow under .github/ invoked this target as of
	@# GH #135, so adding them would buy no CI coverage either — CI reaches these
	@# rows through the regression suite's harness-selftest-func row instead.
	@# The suite's own harness-selftest-func row runs test/harness-selftest.sh
	@# directly, not this target, so nothing here re-enters the regression
	@# prerequisites.
	@bash test/harness-selftest.sh

# Self-test the traceability-matrix VHDL-citation extractor against fixtures
traceability-selftest:
	@perl test/traceability-citations-selftest.pl

# Benchmark the 5 canonical workloads on the fastest core (needs 'make gui-release' first)
bench:
	@bash test/bench/bench.sh

# Configure + build the canonical build/ directory (prerequisite for unit-test)
unit-test-build:
	@# build/jnext is the binary everyone GUI-verifies against, so it must be the Qt build
	@# CLAUDE.md mandates. This target used to configure build/ with NEITHER flag, and
	@# ENABLE_QT_UI defaults OFF — so `make clean` silently downgraded ./build/jnext to an
	@# SDL binary with no main window, and the next person to check the GUI found no window
	@# and concluded their change had broken it. That cost a previous author two capture
	@# runs. Qt6 was never optional here anyway: ENABLE_DEBUGGER already defaults ON and
	@# src/debugger does find_package(Qt6 REQUIRED). The Qt-less configuration keeps its
	@# coverage — `make sdl-release` / `make sdl-debug` still build exactly that.
	@#
	@# The else-branch: the `if` only fires on a fresh build/, so a build/ configured by
	@# hand with other flags would be reused in silence — the same trap, one step removed.
	@# Refuse to build on it rather than hand back a binary that isn't what it claims.
	@if [ ! -f build/CMakeCache.txt ]; then \
		$(CMAKE) -B build -S . \
			-DCMAKE_C_COMPILER=$(CC) \
			-DCMAKE_CXX_COMPILER=$(CXX) \
			-DENABLE_QT_UI=ON \
			-DENABLE_DEBUGGER=ON; \
	else \
		for flag in ENABLE_QT_UI ENABLE_DEBUGGER; do \
			if ! grep -q "^$$flag:BOOL=ON$$" build/CMakeCache.txt; then \
				printf "$(BADGE_FAIL) ERROR $(RESET) build/ is configured with $(BOLD)$$flag=OFF$(RESET).\n"; \
				printf "  ./build/jnext would not be the Qt binary this project mandates.\n"; \
				printf "  Run '$(BOLD)make clean$(RESET)' first, then retry.\n"; \
				exit 1; \
			fi; \
		done; \
	fi
	@$(CMAKE) --build build -j$(JOBS)

# Remove the canonical build/ directory (jnext + test binaries + CMake cache)
unit-test-clean:
	rm -rf build

# Run unit-test and refresh test/SUBSYSTEM-TESTS-STATUS.md from the summary TSV
unit-test-dashboard: unit-test
	@SUMMARY=build/test-summary.tsv; \
	if [ -s $$SUMMARY ] && [ -f test/SUBSYSTEM-TESTS-STATUS.md ]; then \
		if bash test/refresh-subsystem-status.sh $$SUMMARY test/SUBSYSTEM-TESTS-STATUS.md; then \
			printf "$(BOLD)Dashboard refreshed:$(RESET) test/SUBSYSTEM-TESTS-STATUS.md\n\n"; \
		else \
			printf "$(BOLD)Warning:$(RESET) dashboard refresh failed\n\n"; \
		fi; \
	else \
		printf "$(BOLD)Warning:$(RESET) dashboard refresh skipped (no $$SUMMARY — did unit-test produce any rows?)\n\n"; \
	fi; \
	rm -f $$SUMMARY

# Check a worktree has the fixtures the test suites need
worktree-bootstrap:
	@# roms/ holds only the tracked nextboot.rom now, so there is nothing to link:
	@# the SD image lives machine-wide at ~/.jnext/sdcard/ and jnext provisions it
	@# itself (GH #75/#77). This target verifies that master exists and says how to
	@# get it if not.
	@#
	@# Submodules (GH #149): `git worktree add` does NOT populate them, so a fresh
	@# worktree has an EMPTY third_party/spdlog while this target — the one CLAUDE.md
	@# sends every agent through first — reported "ready.". Read from .gitmodules
	@# rather than naming spdlog, so a second submodule is covered the day it is
	@# added; and tested for CONTENT (empty directory) rather than `git submodule
	@# status` state, because content is what the build needs and the content test is
	@# also meaningful in a vendored source tarball, where the status query is silent.
	@#
	@# The failure is REAL and CONDITIONAL ON THE NETWORK, both halves measured in
	@# probe worktrees. With network, an empty submodule self-heals and the build
	@# goes green: CMakeLists.txt:88 runs `git submodule update --init --recursive`
	@# at configure time. Without it — offline, sandboxed, or a transient GitHub
	@# failure — the clone fails, CMakeLists.txt:92 swallows that in a
	@# message(WARNING), and the configure then dies at CMakeLists.txt:144,
	@# `add_subdirectory(third_party/spdlog)`; reproduced under `unshare -rn`.
	@# Either way "ready." was a false claim about a worktree with a ~60 s network
	@# fetch still pending, which is why this reports rather than staying quiet.
	@#
	@# Hence a report, exit 0 — deliberately the same shape as the SD master below,
	@# for the same reason: both are network-provisioned artifacts that something
	@# else in the flow will fetch (CMake here, the suite's sdcard-provision row
	@# there). Failing the target over a self-healing condition would be a false
	@# alarm. And it REPORTS rather than initialising: this target has never mutated
	@# a checkout, and `git submodule update --init` is a write to someone's tree.
	@sd="$$HOME/.jnext/sdcard/cspect-next-1gb-fixed.img"; \
	pending=0; \
	if [ ! -f roms/nextboot.rom ]; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) roms/nextboot.rom missing — this is a tracked file; the checkout is broken\n"; \
		exit 1; \
	fi; \
	printf "  $(CYAN)ok$(RESET) roms/nextboot.rom\n"; \
	n=0; empty=""; \
	for p in $$(git config -f .gitmodules --get-regexp '^submodule\..*\.path$$' 2>/dev/null | awk '{print $$2}'); do \
		n=$$((n + 1)); \
		[ -n "$$(ls -A "$$p" 2>/dev/null)" ] || empty="$$empty $$p"; \
	done; \
	if [ -n "$$empty" ]; then \
		printf "  $(BOLD)missing$(RESET) git submodule(s):%s\n" "$$empty"; \
		printf "$(BOLD)worktree-bootstrap: populate them with:$(RESET)\n"; \
		printf "    git submodule update --init --recursive\n"; \
		printf "  (the first cmake configure runs the same command for you — but silently,\n"; \
		printf "   for ~60 s, and only if the network is up)\n"; \
		pending=1; \
	elif [ "$$n" -gt 0 ]; then \
		printf "  $(CYAN)ok$(RESET) %d git submodule(s) populated\n" "$$n"; \
	fi; \
	if [ -f "$$sd" ]; then \
		printf "  $(CYAN)ok$(RESET) SD master %s\n" "$$sd"; \
	else \
		printf "  $(BOLD)missing$(RESET) SD master %s\n" "$$sd"; \
		printf "$(BOLD)worktree-bootstrap: provision it with:$(RESET)\n"; \
		printf "    ./build/jnext --headless --sdcard-download-confirm --delayed-automatic-exit 1\n"; \
		printf "  (or run the regression suite, whose sdcard-provision row does it for you)\n"; \
		pending=1; \
	fi; \
	if [ "$$pending" -eq 0 ]; then \
		printf "$(BOLD)worktree-bootstrap: ready.$(RESET)\n"; \
	else \
		printf "$(BOLD)worktree-bootstrap: not ready yet — see the item(s) above.$(RESET)\n"; \
	fi

# Count lines of code (excluding comments and blanks), per directory and total
kloc-count:
	printf "\n$(BOLD)Lines of code (excluding comments and blank lines):$(RESET)\n\n"
	total=0; \
	for dir in src/core src/cpu src/memory src/video src/audio src/port src/peripheral src/input src/platform src/debug src/debugger src/gui src/save test; do \
		if [ -d "$$dir" ]; then \
			count=$$(find $$dir -name '*.cpp' -o -name '*.h' | xargs grep -v '^\s*$$' | grep -v '^\s*//' | grep -v '^\s*/\*' | grep -v '^\s*\*' | wc -l); \
			printf "  $(CYAN)$(BOLD)%-30s$(RESET) %6d\n" "$$dir" "$$count"; \
			total=$$((total + count)); \
		fi; \
	done; \
	printf "\n  $(BOLD)%-30s %6d$(RESET)\n\n" "TOTAL" "$$total"

# Regenerate the man page and USAGE.md from doc/man/jnext.1.md (needs pandoc)
docs-man:
	@if ! command -v pandoc >/dev/null 2>&1; then \
	   printf "$(BADGE_FAIL) FAIL $(RESET) pandoc not found. It is a documentation-only\n"; \
	   printf "        dependency: install it to edit the docs, or just use the\n"; \
	   printf "        committed doc/man/jnext.1 and USAGE.md (see BUILD.md).\n"; exit 1; \
	 fi
	pandoc -s -t man $(MAN_SRC) -o $(MAN_OUT)
	pandoc -t gfm --standalone --toc --shift-heading-level-by=1 \
	    --template=doc/man/usage.template \
	    --include-before-body=doc/man/usage-preamble.md \
	    $(MAN_SRC) -o $(USAGE_OUT)
	@$(MAN_FINGERPRINT) > $(MAN_RENDERER)
	printf "$(BADGE_PASS) OK $(RESET) regenerated $(MAN_OUT) and $(USAGE_OUT)\n"

# Fail if the implemented CLI and the documented CLI disagree (issue #43)
cli-check: unit-test-build
	@# docs-check proves the man page and USAGE.md regenerate from jnext.1.md.
	@# It says nothing about whether jnext.1.md describes the CLI main.cpp
	@# actually parses — a gap that shipped five undocumented flags once and a
	@# confidently wrong man page a second time, with every gate green.
	@#
	@# This target closes it. src/core/cli_options.h holds the flag set as DATA,
	@# main.cpp dispatches from that table, and cli_options_test diffs the table
	@# against the man page OPTIONS section in both directions. Deliberate
	@# exceptions (the --sd-card alias) are declared IN the table, never as a
	@# grep exclusion here.
	@#
	@# It is a build-dependent check (the table is C++), which is why it hangs
	@# off unit-test-build rather than off docs-check — docs-check deliberately
	@# needs no compiler. `make unit-test` runs the same suite via
	@# test/unit-tests.conf, so it is covered by both entry points.
	@./build/test/cli_options_test

# Fail if any committed generated document is stale (man page, USAGE.md, guide)
docs-check:
	@# Runs BOTH halves and aggregates, so one stale document never hides the
	@# other. Each half is a self-contained target with its own skip/fail and
	@# its own remediation line: sharing one shell block let a mkdocs-missing
	@# failure print "run 'make docs-man'", which cannot fix it.
	@rc=0; \
	 $(MAKE) --no-print-directory docs-man-check || rc=1; \
	 $(MAKE) --no-print-directory docs-userguide-check || rc=1; \
	 exit $$rc

# Fail if the committed man page / USAGE.md are stale vs doc/man/jnext.1.md
docs-man-check:
	@# One shell block on purpose: a bare `exit 0` in a recipe line of its own
	@# ends only THAT line, and make would carry on into the diff below and
	@# report both outputs "stale" on a host with no pandoc.
	@if ! command -v pandoc >/dev/null 2>&1; then \
	   if [ -n "$$CI" ]; then \
	     printf "$(BADGE_FAIL) FAIL $(RESET) pandoc missing in CI — this check would\n"; \
	     printf "        otherwise skip silently and read as a pass. Install it in the\n"; \
	     printf "        workflow, or drop this step deliberately.\n"; exit 1; \
	   fi; \
	   printf "$(BADGE_SKIP) SKIP $(RESET) pandoc not installed; cannot verify doc freshness\n"; exit 0; \
	 fi; \
	 tmp=$$(mktemp -d); \
	 pandoc -s -t man $(MAN_SRC) -o $$tmp/man.1; \
	 pandoc -t gfm --standalone --toc --shift-heading-level-by=1 \
	     --template=doc/man/usage.template \
	     --include-before-body=doc/man/usage-preamble.md \
	     $(MAN_SRC) -o $$tmp/USAGE.md; \
	 rc=0; compared=0; \
	 here=$$($(MAN_FINGERPRINT)); there=$$(cat $(MAN_RENDERER) 2>/dev/null); \
	 if [ -n "$$there" ] && [ "$$here" != "$$there" ]; then \
	   printf "$(BADGE_SKIP) SKIP $(RESET) different pandoc than generated the committed outputs,\n"; \
	   printf "        so a byte-diff would report a version gap, not staleness.\n"; \
	   printf "        here: $$here / committed: $$there\n"; \
	 else \
	   compared=1; \
	   diff -q $$tmp/man.1 $(MAN_OUT) >/dev/null 2>&1 || { printf "$(BADGE_FAIL) FAIL $(RESET) $(MAN_OUT) is stale\n"; rc=1; }; \
	   diff -q $$tmp/USAGE.md $(USAGE_OUT) >/dev/null 2>&1 || { printf "$(BADGE_FAIL) FAIL $(RESET) $(USAGE_OUT) is stale\n"; rc=1; }; \
	 fi; \
	 rm -rf $$tmp; \
	 if [ $$rc -ne 0 ]; then printf "        run 'make docs-man' and commit the result\n"; \
	 elif [ $$compared -eq 1 ]; then printf "$(BADGE_PASS) OK $(RESET) man page and USAGE.md are up to date\n"; \
	 else printf "$(BADGE_PASS) OK $(RESET) man page regenerates cleanly (staleness NOT compared)\n"; fi; \
	 exit $$rc

# Fail if the committed rendered user guide is stale vs src/doc/user-guide
docs-userguide-check:
	@if ! command -v mkdocs >/dev/null 2>&1; then \
	   if [ -n "$$CI" ]; then \
	     printf "$(BADGE_FAIL) FAIL $(RESET) mkdocs missing in CI — this check would\n"; \
	     printf "        otherwise skip silently and read as a pass. Install it in the\n"; \
	     printf "        workflow, or drop this step deliberately.\n"; exit 1; \
	   fi; \
	   printf "$(BADGE_SKIP) SKIP $(RESET) mkdocs not installed; cannot verify the user guide\n"; exit 0; \
	 fi; \
	 tmp=$$(mktemp -d); \
	 rc=0; \
	 $(GUIDE_BUILD_ENV) mkdocs build --strict --site-dir $$tmp/guide >/dev/null 2>&1 \
	   || { printf "$(BADGE_FAIL) FAIL $(RESET) the user guide does not build\n"; rc=1; }; \
	 here=$$($(GUIDE_FINGERPRINT)); \
	 there=$$(cat $(GUIDE_RENDERER) 2>/dev/null); \
	 compared=0; \
	 if [ $$rc -eq 0 ] && [ "$$here" != "$$there" ]; then \
	   printf "$(BADGE_SKIP) SKIP $(RESET) different mkdocs/material than rendered the committed\n"; \
	   printf "        guide, so a byte-diff would report a version gap, not staleness.\n"; \
	   printf "        here: $$(echo $$here | tr '\\n' ' ') / committed: $$(echo $$there | tr '\\n' ' ')\n"; \
	 elif [ $$rc -eq 0 ]; then \
	   compared=1; \
	   diff -r -q $$tmp/guide $(GUIDE_OUT) >/dev/null 2>&1 \
	     || { printf "$(BADGE_FAIL) FAIL $(RESET) $(GUIDE_OUT) is stale vs $(GUIDE_SRC)\n"; rc=1; }; \
	 fi; \
	 rm -rf $$tmp; \
	 if [ $$rc -ne 0 ]; then printf "        run 'make docs-userguide' and commit the result\n"; \
	 elif [ $$compared -eq 1 ]; then printf "$(BADGE_PASS) OK $(RESET) the rendered user guide is up to date\n"; \
	 else printf "$(BADGE_PASS) OK $(RESET) the user guide builds cleanly (staleness NOT compared)\n"; fi; \
	 exit $$rc

# Render the user guide from src/doc/user-guide into doc/user-guide (needs mkdocs-material)
docs-userguide:
	@if ! command -v mkdocs >/dev/null 2>&1; then \
	   printf "$(BADGE_FAIL) FAIL $(RESET) mkdocs not found. It is a documentation-only\n"; \
	   printf "        dependency: install mkdocs-material from your distribution\n"; \
	   printf "        (Fedora: sudo dnf install mkdocs-material; see BUILD.md). The\n"; \
	   printf "        rendered guide is COMMITTED under doc/user-guide — open\n"; \
	   printf "        doc/user-guide/index.html or run 'make read-userguide'. You\n"; \
	   printf "        only need mkdocs to re-render after editing src/doc/user-guide.\n"; exit 1; \
	 fi
	$(GUIDE_BUILD_ENV) mkdocs build --strict
	@# Record the renderer. The site embeds content-hashed theme assets, so a
	@# different mkdocs-material produces a byte-different tree from identical
	@# sources — the staleness check must know whose output it is comparing.
	@$(GUIDE_FINGERPRINT) > $(GUIDE_RENDERER)
	@printf "$(BADGE_PASS) OK $(RESET) user guide rendered to doc/user-guide\n"
	@printf "        it is committed: commit the regenerated files alongside your change\n"

# Serve the rendered user guide over HTTP so it can be read in a browser
read-userguide:
	@if [ ! -f $(GUIDE_OUT)/index.html ]; then \
	   printf "$(BADGE_FAIL) FAIL $(RESET) doc/user-guide is not rendered yet.\n"; \
	   printf "        Run 'make docs-userguide' first.\n"; exit 1; \
	 fi
	@# Serve the rendered tree itself: mkdocs emits relative URLs (no site_url
	@# is set), so the site works from any directory root without rewriting.
	@# The helper picks the first free port at or above GUIDE_PORT and prints
	@# the URL it actually bound, so a busy 8000 cannot send the reader to a
	@# dead link.
	python3 tools/serve-userguide.py --directory $(GUIDE_OUT) --port $(GUIDE_PORT) --bind 127.0.0.1

# Show current version
version:
	@ver=$$(grep '^version:' version.yaml | awk '{print $$2}'); \
	 printf "$(BOLD)jnext $$ver$(RESET)\n"

# Bump patch version (x.y.Z → x.y.Z+1)
bump-patch:
	@if ! git diff --quiet || ! git diff --cached --quiet; then \
	   printf "$(BOLD)Error: uncommitted changes present. Commit or stash first.$(RESET)\n"; exit 1; \
	 fi
	@ver=$$(grep '^version:' version.yaml | awk '{print $$2}'); \
	 major=$$(echo $$ver | cut -d. -f1); \
	 minor=$$(echo $$ver | cut -d. -f2); \
	 patch=$$(echo $$ver | cut -d. -f3); \
	 patch=$$((patch + 1)); \
	 newver="$$major.$$minor.$$patch"; \
	 rel=""; \
	 if [ -t 0 ]; then \
	   printf "Add v$$newver to releases.yaml (build a public GitHub Release)? [y/N] "; read ans || ans=n; \
	 else ans=n; fi; \
	 case "$$ans" in [yY]*) bash packaging/add-release.sh "v$$newver" && rel="releases.yaml" ;; *) : ;; esac && \
	 printf "version: $$newver\n" > version.yaml && \
	 bash packaging/sync-version.sh "$$newver" && \
	 git add version.yaml $$rel packaging/rpm/jnext.spec packaging/flatpak/io.github.zxjogv.jnext.yml \
	         packaging/assets/io.github.zxjogv.jnext.metainfo.xml packaging/debian/changelog \
	         mkdocs.yml doc/user-guide && \
	 git commit -m "chore: bump version to $$newver" && git tag "v$$newver" && \
	 printf "$(BOLD)Bumped to $$newver and tagged v$$newver$(RESET)\n"

# Bump minor version (x.Y.z → x.Y+1.0)
bump-minor:
	@if ! git diff --quiet || ! git diff --cached --quiet; then \
	   printf "$(BOLD)Error: uncommitted changes present. Commit or stash first.$(RESET)\n"; exit 1; \
	 fi
	@ver=$$(grep '^version:' version.yaml | awk '{print $$2}'); \
	 major=$$(echo $$ver | cut -d. -f1); \
	 minor=$$(echo $$ver | cut -d. -f2); \
	 minor=$$((minor + 1)); \
	 newver="$$major.$$minor.0"; \
	 rel=""; \
	 if [ -t 0 ]; then \
	   printf "Add v$$newver to releases.yaml (build a public GitHub Release)? [y/N] "; read ans || ans=n; \
	 else ans=n; fi; \
	 case "$$ans" in [yY]*) bash packaging/add-release.sh "v$$newver" && rel="releases.yaml" ;; *) : ;; esac && \
	 printf "version: $$newver\n" > version.yaml && \
	 bash packaging/sync-version.sh "$$newver" && \
	 git add version.yaml $$rel packaging/rpm/jnext.spec packaging/flatpak/io.github.zxjogv.jnext.yml \
	         packaging/assets/io.github.zxjogv.jnext.metainfo.xml packaging/debian/changelog \
	         mkdocs.yml doc/user-guide && \
	 git commit -m "chore: bump version to $$newver" && git tag "v$$newver" && \
	 printf "$(BOLD)Bumped to $$newver and tagged v$$newver$(RESET)\n"

# Bump major version (X.y.z → X+1.0.0)
bump-major:
	@if ! git diff --quiet || ! git diff --cached --quiet; then \
	   printf "$(BOLD)Error: uncommitted changes present. Commit or stash first.$(RESET)\n"; exit 1; \
	 fi
	@ver=$$(grep '^version:' version.yaml | awk '{print $$2}'); \
	 major=$$(echo $$ver | cut -d. -f1); \
	 major=$$((major + 1)); \
	 newver="$$major.0.0"; \
	 rel=""; \
	 if [ -t 0 ]; then \
	   printf "Add v$$newver to releases.yaml (build a public GitHub Release)? [y/N] "; read ans || ans=n; \
	 else ans=n; fi; \
	 case "$$ans" in [yY]*) bash packaging/add-release.sh "v$$newver" && rel="releases.yaml" ;; *) : ;; esac && \
	 printf "version: $$newver\n" > version.yaml && \
	 bash packaging/sync-version.sh "$$newver" && \
	 git add version.yaml $$rel packaging/rpm/jnext.spec packaging/flatpak/io.github.zxjogv.jnext.yml \
	         packaging/assets/io.github.zxjogv.jnext.metainfo.xml packaging/debian/changelog \
	         mkdocs.yml doc/user-guide && \
	 git commit -m "chore: bump version to $$newver" && git tag "v$$newver" && \
	 printf "$(BOLD)Bumped to $$newver and tagged v$$newver$(RESET)\n"

# Alias: bump → bump-minor
bump: bump-minor

# Publish the latest release: push commits, then push ONLY the newest tag alone
publish-release:
	@if ! git diff --quiet || ! git diff --cached --quiet; then \
	   printf "$(BOLD)Error: uncommitted changes present. Commit or stash first.$(RESET)\n"; exit 1; \
	 fi
	@branch=$$(git rev-parse --abbrev-ref HEAD); \
	 tag=$$(git tag -l 'v*' | sort -V | tail -1); \
	 if [ -z "$$tag" ]; then printf "$(BOLD)Error: no v* tag found.$(RESET)\n"; exit 1; fi; \
	 public=no; \
	 tagre=$$(printf '%s' "$$tag" | sed 's/\./\\./g'); \
	 if grep -qE "^[[:space:]]*-[[:space:]]*$$tagre[[:space:]]*$$" releases.yaml; then public=yes; fi; \
	 if [ "$$public" = "yes" ] && ! grep -qE "^##[[:space:]]+$$tagre([[:space:]]|\()" ChangeLog; then \
	   printf "$(BOLD)Error:$(RESET) %s is a public release (listed in releases.yaml) but has no ChangeLog entry.\n" "$$tag"; \
	   printf "  Add a '## %s' section to ChangeLog first (differential since the previous public release — see doc/RELEASE-PROTOCOL.md).\n" "$$tag"; \
	   exit 1; \
	 fi; \
	 onorigin=no; \
	 if git ls-remote --tags origin "refs/tags/$$tag" 2>/dev/null | grep -q .; then onorigin=yes; fi; \
	 printf "$(BOLD)Publish plan:$(RESET)\n"; \
	 printf "  push commits : origin %s\n" "$$branch"; \
	 printf "  push tag     : %s (in releases.yaml: %s)\n" "$$tag" "$$public"; \
	 if [ "$$public" != "yes" ]; then \
	   printf "  $(BOLD)WARNING:$(RESET) %s is NOT in releases.yaml — the CI gate will build NO public GitHub Release.\n" "$$tag"; \
	 fi; \
	 if [ "$$onorigin" = "yes" ]; then \
	   printf "  $(BOLD)WARNING:$(RESET) %s already on origin — re-pushing sends no create event and will NOT re-trigger a Release.\n" "$$tag"; \
	 fi; \
	 if [ -t 0 ]; then printf "Proceed? [y/N] "; read ans || ans=n; else ans=n; fi; \
	 case "$$ans" in [yY]*) : ;; *) printf "Aborted.\n"; exit 1 ;; esac; \
	 git push origin "$$branch" && \
	 git push origin "refs/tags/$$tag" && \
	 printf "$(BOLD)Pushed %s + tag %s. Single-tag push triggers the GH Release gate.$(RESET)\n" "$$branch" "$$tag"

# ---------------------------------------------------------------------------
# Packaging (Task 67 follow-up). Each target wraps the packaging inputs under
# packaging/ and CMake's install()/CPack config (see packaging/README.md).
# Linux native targets (src/rpm/deb) are verified on the Fedora dev host;
# win/macos/flatpak guard-and-exit when their tooling/platform is absent.
# ---------------------------------------------------------------------------

# Build directories for these live at the top of this file with every other one
# (BUILD_DIR_RPM_RELEASE / _DEB_RELEASE / _WIN_RELEASE / _MAC_RELEASE).
#
# Wall-clock bound for every macOS packaging phase, so a hang fails fast and
# names the phase instead of blocking a CI job silently (runs 29857249811 /
# 29860430214 each had to be cancelled by hand after 16-21 minutes of no output).
# Absolute path: the cpack phase runs inside a subshell that cd's into the build
# directory, where a relative path stops resolving.
MACOS_BOUND := bash $(CURDIR)/packaging/macos/run-bounded.sh

# Build source packages: v<ver>.tar.gz (rpm/deb source) + jnext-<ver>-src.zip (release); vendors submodules
package-src:
	@mkdir -p build/dist
	bash packaging/make-dist-tarball.sh build/dist

# Build an RPM package via CPack (Fedora/RHEL); needs rpmbuild
package-rpm:
	$(CMAKE) -B $(BUILD_DIR_RPM_RELEASE) -S . \
		-DCMAKE_BUILD_TYPE=Release -DENABLE_QT_UI=ON -DENABLE_TESTS=OFF
	$(CMAKE) --build $(BUILD_DIR_RPM_RELEASE) -j$(JOBS)
	cd $(BUILD_DIR_RPM_RELEASE) && cpack -G RPM
	@printf "$(BOLD)RPM(s) produced:$(RESET)\n"; ls -1 $(BUILD_DIR_RPM_RELEASE)/*.rpm

# Build a DEB package via CPack (Debian/Ubuntu); dep autodetection is weak off-Debian
package-deb:
	$(CMAKE) -B $(BUILD_DIR_DEB_RELEASE) -S . \
		-DCMAKE_BUILD_TYPE=Release -DENABLE_QT_UI=ON -DENABLE_TESTS=OFF
	$(CMAKE) --build $(BUILD_DIR_DEB_RELEASE) -j$(JOBS)
	cd $(BUILD_DIR_DEB_RELEASE) && cpack -G DEB
	@printf "$(BOLD)DEB(s) produced:$(RESET)\n"; ls -1 $(BUILD_DIR_DEB_RELEASE)/*.deb

# Build a Flatpak bundle from packaging/flatpak (needs flatpak-builder + the KDE runtime/SDK)
package-flatpak:
	@if ! command -v flatpak-builder >/dev/null 2>&1; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) flatpak-builder not found.\n"; \
		printf "  Install it first, e.g.: $(BOLD)sudo dnf install flatpak-builder$(RESET)\n"; \
		printf "  (or 'sudo apt install flatpak-builder'), then re-run 'make package-flatpak'.\n"; \
		exit 1; \
	fi
	@# The manifest builds against org.kde.Sdk//6.10 and runs on org.kde.Platform//6.10.
	@# Pre-check both so a missing runtime is a clear "install this" message rather
	@# than a cryptic "org.kde.Sdk/x86_64/6.10 not installed" from deep inside
	@# flatpak-builder (which is what the user hit).
	@miss=""; \
	 flatpak info org.kde.Platform//6.10 >/dev/null 2>&1 || miss="$$miss org.kde.Platform//6.10"; \
	 flatpak info org.kde.Sdk//6.10      >/dev/null 2>&1 || miss="$$miss org.kde.Sdk//6.10"; \
	 if [ -n "$$miss" ]; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) Flatpak runtime/SDK missing:$$miss\n"; \
		printf "  Install from Flathub, then re-run 'make package-flatpak':\n"; \
		printf "  $(BOLD)flatpak install flathub$$miss$(RESET)\n"; \
		printf "  (add the remote first if needed: flatpak remote-add --if-not-exists \\\\\n"; \
		printf "    flathub https://flathub.org/repo/flathub.flatpakrepo)\n"; \
		exit 1; \
	 fi
	@# Build into a local repo, then export a single-file .flatpak bundle so
	@# this target yields a shippable artifact like package-rpm/deb/win do.
	rm -rf $(BUILD_DIR_FPK_RELEASE) $(BUILD_DIR_FPK_RELEASE)-repo
	flatpak-builder --force-clean --user --repo=$(BUILD_DIR_FPK_RELEASE)-repo $(BUILD_DIR_FPK_RELEASE) \
		packaging/flatpak/io.github.zxjogv.jnext.yml
	@ver=$$(grep '^version:' version.yaml | awk '{print $$2}'); \
	 bundle="build/jnext-$$ver-x86_64.flatpak"; \
	 rm -f "$$bundle"; \
	 flatpak build-bundle $(BUILD_DIR_FPK_RELEASE)-repo "$$bundle" io.github.zxjogv.jnext; \
	 printf "$(BOLD)Flatpak bundle produced:$(RESET)\n"; ls -1 "$$bundle"

# Cross-compile + ZIP the Windows build (Fedora MinGW)
package-win: win-release
	@# win-release already bundled the DLLs into $(BUILD_DIR_WIN_RELEASE); we stage a
	@# cleanly-named top-level layout (exe + DLLs + plugin subdirs + qt.conf + docs,
	@# no CMake build junk) and zip that. Not CPack -G ZIP: CPack would apply the
	@# Unix /usr install prefix, giving a broken usr/bin/jnext.exe layout on Windows.
	@# Every step is `&&`-chained, and the structural check below mirrors the four
	@# sibling package-win* recipes (GH #148). Before that, this recipe alone ran
	@# bundle-dlls.sh `;`-terminated with nothing after it that read the bundle, so a
	@# failed bundle zipped the docs, printed "ZIP(s) produced:" and exited 0 — an
	@# artifact with no executable in it, published by release.yml. Required set:
	@# the exe, the Qt6 core DLL, the mandatory qwindows platform plugin (no GUI
	@# without it) and the SDL2+SDL3 pair (SDL2.dll is fedora's sdl2-compat shim,
	@# which LoadLibrary()s SDL3.dll at runtime).
	@ver=$$(grep '^version:' version.yaml | awk '{print $$2}') && \
	 name="jnext-$$ver-windows-x64" && \
	 stage="$(BUILD_DIR_WIN_RELEASE)/dist/$$name" && \
	 rm -rf "$(BUILD_DIR_WIN_RELEASE)/dist" && mkdir -p "$$stage" && \
	 bash packaging/windows/bundle-dlls.sh $(BUILD_DIR_WIN_RELEASE)/jnext.exe "$$stage" && \
	 for f in jnext.exe Qt6Core.dll platforms/qwindows.dll SDL2.dll SDL3.dll; do \
		if [ ! -f "$$stage/$$f" ]; then \
			printf "$(BADGE_FAIL) ERROR $(RESET) $$f missing from the Windows bundle.\n"; exit 1; \
		fi; \
	 done && \
	 cp LICENSE README.md ChangeLog USAGE.md "$$stage"/ && \
	 cp -r doc/user-guide "$$stage"/user-guide && \
	 rm -f "$(BUILD_DIR_WIN_RELEASE)/$$name.zip" && \
	 ( cd "$(BUILD_DIR_WIN_RELEASE)/dist" && zip -rq "../$$name.zip" "$$name" ) && \
	 printf "$(BOLD)ZIP(s) produced:$(RESET)\n" && ls -1 $(BUILD_DIR_WIN_RELEASE)/*.zip

# Cross-compile + ZIP the SDL-only Windows build (Windows 8+ compatible; GH #108)
package-win-sdl: win-sdl-release
	@# Mirrors package-win. Extra structural checks: the SDL-only bundle must carry
	@# no Qt DLL/plugin (that would silently re-raise the OS floor to Windows 10)
	@# and must include the SDL2+SDL3 pair (SDL2.dll is fedora's sdl2-compat shim,
	@# which LoadLibrary()s SDL3.dll at runtime).
	@ver=$$(grep '^version:' version.yaml | awk '{print $$2}') && \
	 name="jnext-$$ver-windows-x64-sdl" && \
	 stage="$(BUILD_DIR_WIN_SDL_RELEASE)/dist/$$name" && \
	 rm -rf "$(BUILD_DIR_WIN_SDL_RELEASE)/dist" && mkdir -p "$$stage" && \
	 bash packaging/windows/bundle-dlls.sh $(BUILD_DIR_WIN_SDL_RELEASE)/jnext.exe "$$stage" && \
	 if ls "$$stage"/Qt6*.dll >/dev/null 2>&1 || [ -d "$$stage/platforms" ]; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) Qt files leaked into the SDL-only bundle.\n"; exit 1; \
	 fi && \
	 for f in jnext.exe SDL2.dll SDL3.dll; do \
		if [ ! -f "$$stage/$$f" ]; then \
			printf "$(BADGE_FAIL) ERROR $(RESET) $$f missing from the SDL-only bundle.\n"; exit 1; \
		fi; \
	 done && \
	 cp LICENSE README.md ChangeLog USAGE.md "$$stage"/ && \
	 cp -r doc/user-guide "$$stage"/user-guide && \
	 rm -f "$(BUILD_DIR_WIN_SDL_RELEASE)/$$name.zip" && \
	 ( cd "$(BUILD_DIR_WIN_SDL_RELEASE)/dist" && zip -rq "../$$name.zip" "$$name" ) && \
	 printf "$(BOLD)ZIP(s) produced:$(RESET)\n" && ls -1 $(BUILD_DIR_WIN_SDL_RELEASE)/*.zip

# Cross-compile + ZIP the Qt5 full-GUI Windows build (Win7/8 legacy leg; GH #108 Phase A)
package-win-qt5: win-qt5-release
	@# Mirrors package-win. The ZIP is named -legacy (the audience) not -qt5 (the
	@# toolchain) — that is the published GitHub asset name, keep it in step with
	@# README.md. Structural checks: Qt5 core DLL + qwindows plugin must
	@# be present; NO Qt6 DLL may leak in (a mixed bundle would re-raise the OS
	@# floor to Windows 10 via Qt6Gui's d3d12 import).
	@ver=$$(grep '^version:' version.yaml | awk '{print $$2}') && \
	 name="jnext-$$ver-windows-x64-legacy" && \
	 stage="$(BUILD_DIR_WIN_QT5_RELEASE)/dist/$$name" && \
	 rm -rf "$(BUILD_DIR_WIN_QT5_RELEASE)/dist" && mkdir -p "$$stage" && \
	 bash packaging/windows/bundle-dlls.sh $(BUILD_DIR_WIN_QT5_RELEASE)/jnext.exe "$$stage" && \
	 if ls "$$stage"/Qt6*.dll >/dev/null 2>&1; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) Qt6 DLLs leaked into the Qt5 bundle.\n"; exit 1; \
	 fi && \
	 for f in jnext.exe Qt5Core.dll platforms/qwindows.dll SDL2.dll SDL3.dll; do \
		if [ ! -f "$$stage/$$f" ]; then \
			printf "$(BADGE_FAIL) ERROR $(RESET) $$f missing from the Qt5 bundle.\n"; exit 1; \
		fi; \
	 done && \
	 cp LICENSE README.md ChangeLog USAGE.md "$$stage"/ && \
	 cp -r doc/user-guide "$$stage"/user-guide && \
	 rm -f "$(BUILD_DIR_WIN_QT5_RELEASE)/$$name.zip" && \
	 ( cd "$(BUILD_DIR_WIN_QT5_RELEASE)/dist" && zip -rq "../$$name.zip" "$$name" ) && \
	 printf "$(BOLD)ZIP(s) produced:$(RESET)\n" && ls -1 $(BUILD_DIR_WIN_QT5_RELEASE)/*.zip

# Cross-compile + ZIP the Qt5 full-GUI 32-bit (i686) Windows build (Win7 32-bit leg; GH #108 Phase C)
package-win32-qt5: win32-qt5-release
	@# Mirrors package-win-qt5 exactly, including its structural checks (Qt5 core
	@# DLL + qwindows present, no Qt6 leak). PUBLISHED release artifact — the third
	@# Windows leg of the final lineup (x64-Qt6, x64-Qt5, i686-Qt5): see
	@# doc/design/WINDOWS-COMPAT-PLAN.md §7 Phase C. ZIP named -legacy, not -qt5
	@# (same reason as the x64 leg).
	@ver=$$(grep '^version:' version.yaml | awk '{print $$2}') && \
	 name="jnext-$$ver-windows-x86-legacy" && \
	 stage="$(BUILD_DIR_WIN32_QT5_RELEASE)/dist/$$name" && \
	 rm -rf "$(BUILD_DIR_WIN32_QT5_RELEASE)/dist" && mkdir -p "$$stage" && \
	 bash packaging/windows/bundle-dlls.sh $(BUILD_DIR_WIN32_QT5_RELEASE)/jnext.exe "$$stage" && \
	 if ls "$$stage"/Qt6*.dll >/dev/null 2>&1; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) Qt6 DLLs leaked into the Qt5 bundle.\n"; exit 1; \
	 fi && \
	 for f in jnext.exe Qt5Core.dll platforms/qwindows.dll SDL2.dll SDL3.dll; do \
		if [ ! -f "$$stage/$$f" ]; then \
			printf "$(BADGE_FAIL) ERROR $(RESET) $$f missing from the Qt5 bundle.\n"; exit 1; \
		fi; \
	 done && \
	 cp LICENSE README.md ChangeLog USAGE.md "$$stage"/ && \
	 cp -r doc/user-guide "$$stage"/user-guide && \
	 rm -f "$(BUILD_DIR_WIN32_QT5_RELEASE)/$$name.zip" && \
	 ( cd "$(BUILD_DIR_WIN32_QT5_RELEASE)/dist" && zip -rq "../$$name.zip" "$$name" ) && \
	 printf "$(BOLD)ZIP(s) produced:$(RESET)\n" && ls -1 $(BUILD_DIR_WIN32_QT5_RELEASE)/*.zip

# Cross-compile + ZIP the SDL-only 32-bit (i686) Windows build — repo-internal (GH #108 Phase C)
package-win32-sdl: win32-sdl-release
	@# Mirrors package-win-sdl exactly, including its structural checks (no Qt leak,
	@# SDL2+SDL3 pair present). Naming follows the x64 convention: -windows-x86-sdl.
	@# REPO-INTERNAL (owner decision 2026-07-26): not a published release artifact —
	@# the published 32-bit leg will be i686-Qt5 (WINDOWS-COMPAT-PLAN.md §7 Phase C).
	@# Exercised in CI by the package-win32-sdl row of `make package-test`.
	@ver=$$(grep '^version:' version.yaml | awk '{print $$2}') && \
	 name="jnext-$$ver-windows-x86-sdl" && \
	 stage="$(BUILD_DIR_WIN32_SDL_RELEASE)/dist/$$name" && \
	 rm -rf "$(BUILD_DIR_WIN32_SDL_RELEASE)/dist" && mkdir -p "$$stage" && \
	 bash packaging/windows/bundle-dlls.sh $(BUILD_DIR_WIN32_SDL_RELEASE)/jnext.exe "$$stage" && \
	 if ls "$$stage"/Qt6*.dll >/dev/null 2>&1 || [ -d "$$stage/platforms" ]; then \
		printf "$(BADGE_FAIL) ERROR $(RESET) Qt files leaked into the SDL-only bundle.\n"; exit 1; \
	 fi && \
	 for f in jnext.exe SDL2.dll SDL3.dll; do \
		if [ ! -f "$$stage/$$f" ]; then \
			printf "$(BADGE_FAIL) ERROR $(RESET) $$f missing from the SDL-only bundle.\n"; exit 1; \
		fi; \
	 done && \
	 cp LICENSE README.md ChangeLog USAGE.md "$$stage"/ && \
	 cp -r doc/user-guide "$$stage"/user-guide && \
	 rm -f "$(BUILD_DIR_WIN32_SDL_RELEASE)/$$name.zip" && \
	 ( cd "$(BUILD_DIR_WIN32_SDL_RELEASE)/dist" && zip -rq "../$$name.zip" "$$name" ) && \
	 printf "$(BOLD)ZIP(s) produced:$(RESET)\n" && ls -1 $(BUILD_DIR_WIN32_SDL_RELEASE)/*.zip

# Build a macOS .dmg via CPack DragNDrop (Darwin only)
package-macos:
	@# The whole recipe is one shell invocation so the non-Darwin early-exit
	@# actually stops it — a bare `exit 0` on its own recipe line would only end
	@# that line and make would still run the build+cpack lines that follow.
	@if [ "$$(uname -s)" != "Darwin" ]; then \
		printf "$(BADGE_SKIP) SKIP $(RESET) macOS packaging requires a Mac (or the GitHub Actions\n"; \
		printf "  macos-latest runner — see the macos job in .github/workflows/release.yml).\n"; \
		printf "  It cannot be produced on this $$(uname -s) host.\n"; \
		exit 0; \
	fi; \
	$(MACOS_BOUND) 300 "cmake configure (mac-release)" \
		$(CMAKE) -B $(BUILD_DIR_MAC_RELEASE) -S . \
		-DCMAKE_BUILD_TYPE=Release -DENABLE_QT_UI=ON -DENABLE_TESTS=OFF \
		-DMACOS_APP_BUNDLE=ON && \
	$(MACOS_BOUND) 2400 "cmake build (mac-release)" \
		$(CMAKE) --build $(BUILD_DIR_MAC_RELEASE) -j$(JOBS) && \
	( cd $(BUILD_DIR_MAC_RELEASE) && $(MACOS_BOUND) 900 "cpack -G DragNDrop" cpack -G DragNDrop ) && \
	$(MAKE) verify-macos-dmg

# Prove the shipped .dmg is self-contained: mount it and walk the .app with otool (Darwin only)
verify-macos-dmg:
	@# The staging install already runs verify-bundle.sh (see the APPLE branch in
	@# CMakeLists.txt), but that checks the tree cpack was ABOUT to package. This
	@# checks what actually shipped, read out of the disk image the user downloads —
	@# the artifact GH #46 was reported against. Cheap, and the only end-to-end
	@# statement we can make without a second Mac.
	@#
	@# `yes |` is load-bearing: CPACK_RESOURCE_FILE_LICENSE makes CPack embed a
	@# Software License Agreement in the .dmg, and hdiutil will not accept one
	@# non-interactively — it answers "hdiutil: attach canceled" and mounts nothing
	@# (run 29854836676). CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE is also turned OFF
	@# so users are not prompted either; this keeps the check working regardless.
	@#
	@# There is deliberately NO launch smoke test here, and it is not an oversight.
	@# One was tried and REMOVED on evidence (runs 29859539303 / 29860430214 /
	@# 29863761709):
	@#
	@#   * It cannot prove the thing GH #46 is about. It would run on the machine
	@#     that BUILT the package, where Homebrew is present, so a missed dependency
	@#     would be silently satisfied. verify-bundle.sh proves self-containment
	@#     structurally, and it runs twice — once on the staged bundle and once on
	@#     the bundle inside the mounted .dmg.
	@#   * It hangs, in macOS, not in jnext. DYLD_PRINT_LIBRARIES showed dyld getting
	@#     as far as AppleParavirtGPUMetalIOGPUFamily and IOGPU — the GPU stack on a
	@#     headless paravirtualised CI VM — and then stopping dead. jnext writes its
	@#     version banner to stderr BEFORE parsing any argument (main.cpp), and no
	@#     banner ever appeared, so the process never reached main(): the block is
	@#     pre-main, in dyld/AMFI, and nothing in this repo can fix it. Launching the
	@#     same binary as a bare executable takes ~60ms in the Smoke test step.
	@#
	@# It was deleted rather than made non-fatal. A check that is allowed to fail
	@# silently is worse than no check: it reads as coverage and provides none.
	@if [ "$$(uname -s)" != "Darwin" ]; then \
		printf "$(BADGE_SKIP) SKIP $(RESET) verifying a .dmg requires a Mac (hdiutil/otool).\n"; \
		exit 0; \
	fi; \
	set -e; \
	dmg=$$(ls -1 $(BUILD_DIR_MAC_RELEASE)/*.dmg 2>/dev/null | head -1); \
	if [ -z "$$dmg" ]; then echo "error: no .dmg in $(BUILD_DIR_MAC_RELEASE)" >&2; exit 1; fi; \
	mnt=$$(mktemp -d); \
	trap 'hdiutil detach "$$mnt" -quiet -force >/dev/null 2>&1; rmdir "$$mnt" 2>/dev/null || true' EXIT; \
	yes | $(MACOS_BOUND) 120 "hdiutil attach" \
		hdiutil attach "$$dmg" -nobrowse -readonly -noverify -noautoopen -mountpoint "$$mnt" >/dev/null; \
	$(MACOS_BOUND) 300 "verify-bundle (mounted dmg)" \
		bash packaging/macos/verify-bundle.sh "$$mnt/jnext.app" </dev/null; \
	printf "$(BOLD)dmg verified:$(RESET) $$dmg\n"

# Self-test packaging-test.sh's failure path: a failing sub-test's log must surface inline (GH #80)
packaging-selftest:
	@bash test/packaging/packaging-selftest.sh

# Integration-test every package target (src/rpm/deb/win/flatpak) — tooling-guarded, macOS excluded
package-test: packaging-selftest
	bash test/packaging/packaging-test.sh

# Contract-test the packaging scripts + package-* recipes (no builds) — hermetic, ~4s
package-contract-test:
	@bash test/packaging/packaging-test.sh --contracts-only
