#!/usr/bin/env bash
#
# verify-permissions.sh [<target>]
#
# Prove that the BUILT Flatpak carries every sandbox permission jnext needs in
# order to do its job. Today that is exactly one: `--share=network`.
#
# GH #271. jnext is a NETWORKED application — it is not "an emulator that also
# happens to download something once":
#
#   * the SD-card provisioner fetches the NextZXOS distro zip over HTTPS
#     (src/core/sdcard_provisioner_net_curl.cpp), which is how a first run
#     obtains every ROM the emulator needs;
#   * the ESP-01 WiFi emulation (GH #25) opens real TCP/UDP sockets to the real
#     internet and listens for inbound connections
#     (src/esp01/src/esp_socket_posix.cpp — getaddrinfo/socket/connect/bind),
#     which is how a guest program reaches a BBS such as nx.nxtel.org.
#
# The shipped manifest granted ipc/x11/wayland/pulseaudio/dri/home and NOT
# network, so a Flatpak install of jnext 1.0.1 had no DNS at all: the reporter
# saw "Could not resolve hostname" from libcurl while `wget` of the same URL
# worked outside the sandbox, and reasonably concluded the DOWNLOADER was
# broken. The ESP-01 half of the same bug went unreported only because you have
# to try NXtel inside a Flatpak to notice.
#
# Why this reads the ARTIFACT and not the manifest: what ships is the built
# bundle's `metadata`, generated by flatpak-builder from `finish-args`, and
# that is what `flatpak run` enforces. A grep of the YAML proves only that a
# string is in a file — it cannot see a finish-arg that flatpak-builder
# rejected, a manifest that is not the one that got built, or a bundle exported
# from a stale build directory. So every accepted target below resolves to a
# real `[Context]` section produced by a real build.
#
# Targets (auto-detected, in this order):
#
#   <dir>            a flatpak-builder app directory (contains `metadata`)
#   <file> "metadata"  that metadata file directly
#   <file> *.flatpak   a single-file bundle: installed into a THROWAWAY
#                      FLATPAK_USER_DIR and read back with `flatpak info
#                      --show-permissions`, i.e. exactly what a user's machine
#                      would report after installing it. Nothing is written to
#                      the caller's own flatpak installation.
#   <app-id>         an already-installed application (`flatpak info
#                    --show-permissions`)
#
# With no argument it looks for build/jnext-*.flatpak (what `make
# package-flatpak` produces).
#
# It must FAIL the build, never warn: a permission this app cannot run without
# is not a style preference.
#
set -euo pipefail

# The permissions the shipped app must carry, as `shared=` tokens of the
# metadata [Context] section. One entry today; add a line here when another
# permission becomes load-bearing (and say in the manifest why it is needed).
REQUIRED_SHARED=(network)

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

usage() {
    echo "usage: $0 [<app-dir>|<metadata-file>|<bundle.flatpak>|<app-id>]" >&2
    exit 2
}

[ "$#" -le 1 ] || usage

target=${1:-}
if [ -z "$target" ]; then
    target=$(ls -1 build/jnext-*.flatpak 2>/dev/null | head -1)
    [ -n "$target" ] || die "no target given and no build/jnext-*.flatpak found"
fi

WORK=""
# `return 0` is load-bearing: bash takes the EXIT trap's last command status as
# the script's exit status, so a cleanup that ends in a false test (the common
# case — nothing to remove) would turn a PASS into a silent exit 1. Caught by
# FPKP-01/02/03/11, which is what those rows are for.
cleanup() { [ -n "$WORK" ] && rm -rf "$WORK"; return 0; }
trap cleanup EXIT

# ---------------------------------------------------------------------------
# Resolve the target to the text of a `flatpak info --show-permissions`-shaped
# [Context] section.
# ---------------------------------------------------------------------------
context_src=""   # human-readable description of where the text came from
context_txt=""

need_flatpak() {
    command -v flatpak >/dev/null 2>&1 \
        || die "flatpak not found — cannot read permissions of '$target'"
}

if [ -d "$target" ]; then
    [ -f "$target/metadata" ] \
        || die "'$target' is a directory but holds no 'metadata' (not a flatpak-builder app dir)"
    context_src="$target/metadata"
    context_txt=$(cat "$context_src")
elif [ -f "$target" ] && [ "$(basename "$target")" = metadata ]; then
    context_src=$target
    context_txt=$(cat "$context_src")
elif [ -f "$target" ]; then
    # A bundle. Install it into a throwaway installation and ask flatpak what
    # the installed app may do — the same question a user's machine answers.
    # The runtime is NOT pulled: `flatpak info` needs only the app's own
    # metadata, and --no-deps keeps this off the network entirely.
    need_flatpak
    WORK=$(mktemp -d)
    inst_log=$WORK/install.log
    if ! FLATPAK_USER_DIR="$WORK/flatpak" \
         timeout --kill-after=5s 300s \
         flatpak install --user --bundle --noninteractive --no-deps \
             "$target" >"$inst_log" 2>&1; then
        sed -e 's/^/  | /' "$inst_log" >&2
        die "could not install bundle '$target' into a throwaway installation"
    fi
    app_id=$(FLATPAK_USER_DIR="$WORK/flatpak" \
             flatpak list --user --app --columns=application 2>/dev/null | head -1)
    [ -n "$app_id" ] || die "bundle '$target' installed no application"
    context_src="$target (installed as $app_id)"
    context_txt=$(FLATPAK_USER_DIR="$WORK/flatpak" \
                  flatpak info --user --show-permissions "$app_id" 2>/dev/null) \
        || die "could not read permissions of '$app_id' from '$target'"
else
    # Not a path that exists: treat it as an installed application id.
    need_flatpak
    context_src="installed app $target"
    context_txt=$(flatpak info --show-permissions "$target" 2>/dev/null) \
        || die "'$target' is neither an existing path nor an installed flatpak"
fi

[ -n "$context_txt" ] || die "no permission data read from $context_src"

# ---------------------------------------------------------------------------
# Parse the [Context] section's `shared=` list.
#
# Section-scoped ON PURPOSE. A plain `grep -q network` over the whole file
# passes on a `filesystems=/srv/network` line, on a `shared=networking;` typo,
# and on a `shared=network;` that belongs to some OTHER section — none of which
# grants the app a network namespace. The contract suite pins all three.
# ---------------------------------------------------------------------------
shared_line=$(awk '
    /^\[/        { in_ctx = ($0 == "[Context]"); next }
    in_ctx && /^shared[ \t]*=/ { sub(/^shared[ \t]*=[ \t]*/, ""); print; exit }
' <<<"$context_txt")

missing=()
for want in "${REQUIRED_SHARED[@]}"; do
    found=0
    # Split on ';' and compare WHOLE tokens.
    IFS=';' read -r -a tokens <<<"$shared_line"
    for tok in "${tokens[@]}"; do
        # shellcheck disable=SC2001
        tok=$(sed -e 's/^[ \t]*//' -e 's/[ \t]*$//' <<<"$tok")
        [ "$tok" = "$want" ] && { found=1; break; }
    done
    [ "$found" -eq 1 ] || missing+=("$want")
done

if [ "${#missing[@]}" -ne 0 ]; then
    printf 'error: the built Flatpak is MISSING required permission(s): %s\n' \
        "${missing[*]}" >&2
    printf '  read from: %s\n' "$context_src" >&2
    printf '  [Context] shared=%s\n' "${shared_line:-<absent>}" >&2
    printf '  Add the matching finish-arg to packaging/flatpak/io.github.zxjogv.jnext.yml\n' >&2
    printf '  (e.g. --share=network) and rebuild. jnext downloads its SD-card image\n' >&2
    printf '  and runs the ESP-01 WiFi emulation over real sockets; without the\n' >&2
    printf '  network permission both fail with "Could not resolve hostname" (GH #271).\n' >&2
    exit 1
fi

printf 'flatpak permissions OK: shared=%s (from %s)\n' "$shared_line" "$context_src"
