#pragma once

#include <cstddef>
#include <cstdint>

// FPGA boot ROM (8 KB) embedded into the jnext binary at link time.
//
// This mirrors the on-FPGA flash IPL of a real ZX Spectrum Next, which
// is silicon-baked and never touches the SD card. Embedding here means
// jnext is self-contained for the boot stage: no CLI flag and no SD
// lookup needed for the bootloader overlay at 0x0000-0x1FFF.
//
// User decision (2026-05-04, Task 8 Multiface plan, Wave 0.1 + 0.3):
// nextboot.rom is the only ROM that's silicon-baked; everything else
// comes from the user-supplied SD-card image (--sd-card, mandatory) via
// src/core/sd_rom_extractor.{h,cpp}.
//
// The three `_binary_roms_nextboot_rom_*` symbols are auto-generated by
// the `objcopy --input-target=binary` recipe in src/core/CMakeLists.txt
// — see the embed-nextboot custom_command there.

extern "C" {
    extern const uint8_t _binary_roms_nextboot_rom_start[];
    extern const uint8_t _binary_roms_nextboot_rom_end[];
}

inline const uint8_t* embedded_nextboot_rom_data() {
    return _binary_roms_nextboot_rom_start;
}

inline std::size_t embedded_nextboot_rom_size() {
    return static_cast<std::size_t>(
        _binary_roms_nextboot_rom_end - _binary_roms_nextboot_rom_start);
}
