# Portable binary-to-C-array embedder, run in CMake script mode:
#   cmake -DROM_IN=<in.bin> -DROM_OUT=<out.c> -P embed_rom.cmake
#
# Replaces the objcopy `--input-target=binary` recipe, which is not portable:
# macOS ships no GNU objcopy able to emit a Mach-O object with the `_binary_*`
# symbols, and the arm64 macOS runner also breaks the `i386:x86-64` arch flag.
# A generated C array compiles identically on Linux (ELF), Windows (MinGW/PE)
# and macOS (Mach-O) with no toolchain assumptions. The symbol names are
# ordinary C identifiers, so the compiler applies each platform's mangling
# consistently to both definition and reference.
file(READ "${ROM_IN}" _hex HEX)
string(LENGTH "${_hex}" _hexlen)
math(EXPR _bytes "${_hexlen} / 2")
# "aabbcc..." -> "0xaa,0xbb,0xcc,"
string(REGEX REPLACE "(..)" "0x\\1," _arr "${_hex}")
file(WRITE "${ROM_OUT}"
"/* Auto-generated by embed_rom.cmake from ${ROM_IN}. Do not edit. */\n"
"#include <stdint.h>\n"
"const uint8_t nextboot_rom_data[${_bytes}] = { ${_arr} };\n"
"const unsigned nextboot_rom_size = ${_bytes}u;\n")
