#!/usr/bin/env bash
# Generate 48rom.map from the Spectrum ROM map data.
# Source: https://skoolkid.github.io/rom/maps/all.html
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="${SCRIPT_DIR}/../data/48rom.map"

mkdir -p "$(dirname "$OUTPUT")"

perl -e '
my $raw = <<'"'"'END'"'"';
0000 THE '"'"'START'"'"'
0008 THE '"'"'ERROR'"'"' RESTART
0010 THE '"'"'PRINT A CHARACTER'"'"' RESTART
0018 THE '"'"'COLLECT CHARACTER'"'"' RESTART
0020 THE '"'"'COLLECT NEXT CHARACTER'"'"' RESTART
0028 THE '"'"'CALCULATOR'"'"' RESTART
0030 THE '"'"'MAKE BC SPACES'"'"' RESTART
0038 THE '"'"'MASKABLE INTERRUPT'"'"' ROUTINE
END
print $raw;
' > /dev/null

# Use a Perl script for the heavy lifting — inline heredoc with raw data
perl - "$OUTPUT" <<'PERL_SCRIPT'
use strict;
use warnings;

my $output = $ARGV[0];

my @raw = split /\n/, <<'MAP_DATA';
0000 THE 'START'
0008 THE 'ERROR' RESTART
0010 THE 'PRINT A CHARACTER' RESTART
0018 THE 'COLLECT CHARACTER' RESTART
0020 THE 'COLLECT NEXT CHARACTER' RESTART
0028 THE 'CALCULATOR' RESTART
0030 THE 'MAKE BC SPACES' RESTART
0038 THE 'MASKABLE INTERRUPT' ROUTINE
0053 THE 'ERROR-2' ROUTINE
0066 THE 'NON-MASKABLE INTERRUPT' ROUTINE
0074 THE 'CH-ADD+1' SUBROUTINE
007D THE 'SKIP-OVER' SUBROUTINE
0095 THE TOKEN TABLE
0205 THE KEY TABLES
028E THE 'KEYBOARD SCANNING' SUBROUTINE
02BF THE 'KEYBOARD' SUBROUTINE
031E THE 'K-TEST' SUBROUTINE
0333 THE 'KEYBOARD DECODING' SUBROUTINE
03B5 THE 'BEEPER' SUBROUTINE
03F8 THE 'BEEP' COMMAND ROUTINE
046E THE 'SEMI-TONE' TABLE
04C2 THE 'SA-BYTES' SUBROUTINE
053F THE 'SA/LD-RET' SUBROUTINE
0556 THE 'LD-BYTES' SUBROUTINE
05E3 THE 'LD-EDGE-2' AND 'LD-EDGE-1' SUBROUTINES
0605 THE 'SAVE, LOAD, VERIFY and MERGE' COMMAND ROUTINES
07CB THE 'VERIFY' CONTROL ROUTINE
0802 THE 'LOAD A DATA BLOCK' SUBROUTINE
0808 THE 'LOAD' CONTROL ROUTINE
08B6 THE 'MERGE' CONTROL ROUTINE
092C THE 'MERGE A LINE OR A VARIABLE' SUBROUTINE
0970 THE 'SAVE' CONTROL ROUTINE
09A1 THE CASSETTE MESSAGES
09F4 THE 'PRINT-OUT' ROUTINES
0A11 THE 'CONTROL CHARACTER' TABLE
0A23 THE 'CURSOR LEFT' SUBROUTINE
0A3D THE 'CURSOR RIGHT' SUBROUTINE
0A4F THE 'CARRIAGE RETURN' SUBROUTINE
0A5F THE 'PRINT COMMA' SUBROUTINE
0A69 THE 'PRINT A QUESTION MARK' SUBROUTINE
0A6D THE 'CONTROL CHARACTERS WITH OPERANDS' ROUTINE
0AD9 PRINTABLE CHARACTER CODES
0ADC THE 'POSITION STORE' SUBROUTINE
0B03 THE 'POSITION FETCH' SUBROUTINE
0B24 THE 'PRINT ANY CHARACTER(S)' SUBROUTINE
0BDB THE 'SET ATTRIBUTE BYTE' SUBROUTINE
0C0A THE 'MESSAGE PRINTING' SUBROUTINE
0C3B THE 'PO-SAVE' SUBROUTINE
0C41 THE 'TABLE SEARCH' SUBROUTINE
0C55 THE 'TEST FOR SCROLL' SUBROUTINE
0D4D THE 'TEMPORARY COLOUR ITEMS' SUBROUTINE
0D6B THE 'CLS' COMMAND ROUTINE
0DAF THE 'CLEARING THE WHOLE DISPLAY AREA' SUBROUTINE
0DD9 THE 'CL-SET' SUBROUTINE
0DFE THE 'SCROLLING' SUBROUTINE
0E44 THE 'CLEAR LINES' SUBROUTINE
0E88 THE 'CL-ATTR' SUBROUTINE
0E9B THE 'CL-ADDR' SUBROUTINE
0EAC THE 'COPY' COMMAND ROUTINE
0ECD THE 'COPY-BUFF' SUBROUTINE
0EDF THE 'CLEAR PRINTER BUFFER' SUBROUTINE
0EF4 THE 'COPY-LINE' SUBROUTINE
0F2C THE 'EDITOR' ROUTINES
0FA0 THE 'EDITING KEYS' TABLE
0FA9 THE 'EDIT KEY' SUBROUTINE
0FF3 THE 'CURSOR DOWN EDITING' SUBROUTINE
1007 THE 'CURSOR LEFT EDITING' SUBROUTINE
100C THE 'CURSOR RIGHT EDITING' SUBROUTINE
1015 THE 'DELETE EDITING' SUBROUTINE
101E THE 'ED-IGNORE' SUBROUTINE
1024 THE 'ENTER EDITING' SUBROUTINE
1031 THE 'ED-EDGE' SUBROUTINE
1059 THE 'CURSOR UP EDITING' SUBROUTINE
1076 THE 'ED-SYMBOL' SUBROUTINE
107F THE 'ED-ERROR' SUBROUTINE
1097 THE 'CLEAR-SP' SUBROUTINE
10A8 THE 'KEYBOARD INPUT' SUBROUTINE
111D THE 'LOWER SCREEN COPYING' SUBROUTINE
1190 THE 'SET-HL' AND 'SET-DE' SUBROUTINES
11A7 THE 'REMOVE-FP' SUBROUTINE
11B7 THE 'NEW' COMMAND ROUTINE
12A2 THE 'MAIN EXECUTION' LOOP
1391 THE REPORT MESSAGES
1539 THE COPYRIGHT MESSAGE
155D THE 'MAIN-ADD' SUBROUTINE
15AF THE 'INITIAL CHANNEL INFORMATION'
15C6 THE 'INITIAL STREAM DATA'
15D4 THE 'WAIT-KEY' SUBROUTINE
15E6 THE 'INPUT-AD' SUBROUTINE
15EF THE 'MAIN PRINTING' SUBROUTINE
1601 THE 'CHAN-OPEN' SUBROUTINE
1615 THE 'CHAN-FLAG' SUBROUTINE
162D THE 'CHANNEL CODE LOOK-UP' TABLE
1634 THE 'CHANNEL K FLAG' SUBROUTINE
1642 THE 'CHANNEL S FLAG' SUBROUTINE
164D THE 'CHANNEL P FLAG' SUBROUTINE
1652 THE 'MAKE-ROOM' SUBROUTINE
1664 THE 'POINTERS' SUBROUTINE
168F THE 'COLLECT A LINE NUMBER' SUBROUTINE
169E THE 'RESERVE' SUBROUTINE
16B0 THE 'SET-MIN' SUBROUTINE
16D4 THE 'RECLAIM THE EDIT-LINE' SUBROUTINE
16DB THE 'INDEXER' SUBROUTINE
16E5 THE 'CLOSE #' COMMAND ROUTINE
1701 THE 'CLOSE-2' SUBROUTINE
1716 THE 'CLOSE STREAM LOOK-UP' TABLE
171C THE 'CLOSE STREAM' SUBROUTINE
171E THE 'STREAM DATA' SUBROUTINE
1736 THE 'OPEN #' COMMAND ROUTINE
175D THE 'OPEN-2' SUBROUTINE
177A THE 'OPEN STREAM LOOK-UP' TABLE
1781 THE 'OPEN-K' SUBROUTINE
1785 THE 'OPEN-S' SUBROUTINE
1789 THE 'OPEN-P' SUBROUTINE
1793 THE 'CAT, ERASE, FORMAT and MOVE' COMMAND ROUTINES
1795 THE 'LIST and LLIST' COMMAND ROUTINES
17F5 THE 'LLIST' ENTRY POINT
17F9 THE 'LIST' ENTRY POINT
1855 THE 'PRINT A WHOLE BASIC LINE' SUBROUTINE
18B6 THE 'NUMBER' SUBROUTINE
18C1 THE 'PRINT A FLASHING CHARACTER' SUBROUTINE
18E1 THE 'PRINT THE CURSOR' SUBROUTINE
190F THE 'LN-FETCH' SUBROUTINE
1925 THE 'PRINTING CHARACTERS IN A BASIC LINE' SUBROUTINE
196E THE 'LINE-ADDR' SUBROUTINE
1980 THE 'COMPARE LINE NUMBERS' SUBROUTINE
198B THE 'FIND EACH STATEMENT' SUBROUTINE
19B8 THE 'NEXT-ONE' SUBROUTINE
19DD THE 'DIFFERENCE' SUBROUTINE
19E5 THE 'RECLAIMING' SUBROUTINE
19FB THE 'E-LINE-NO' SUBROUTINE
1A1B THE 'REPORT AND LINE NUMBER PRINTING' SUBROUTINE
1A48 THE SYNTAX TABLES
1B17 THE 'MAIN PARSER' OF THE BASIC INTERPRETER
1B28 THE STATEMENT LOOP
1B6F THE 'SEPARATOR' SUBROUTINE
1B76 THE 'STMT-RET' SUBROUTINE
1B8A THE 'LINE-RUN' ENTRY POINT
1B9E THE 'LINE-NEW' SUBROUTINE
1BB2 THE 'REM' COMMAND ROUTINE
1BB3 THE 'LINE-END' ROUTINE
1BBF THE 'LINE-USE' ROUTINE
1BD1 THE 'NEXT-LINE' ROUTINE
1BEE THE 'CHECK-END' SUBROUTINE
1BF4 THE 'STMT-NEXT' ROUTINE
1C01 THE 'COMMAND CLASS' TABLE
1C0D THE 'COMMAND CLASSES - +00, +03 and +05'
1C1F THE 'COMMAND CLASS +01' ROUTINE
1C22 THE 'VARIABLE IN ASSIGNMENT' SUBROUTINE
1C4E THE 'COMMAND CLASS +02' ROUTINE
1C56 THE 'FETCH A VALUE' SUBROUTINE
1C6C THE 'COMMAND CLASS +04' ROUTINE
1C79 THE 'EXPECT NUMERIC/STRING EXPRESSIONS' SUBROUTINE
1C96 THE 'SET PERMANENT COLOURS' SUBROUTINE
1CBE THE 'COMMAND CLASS +09' ROUTINE
1CDB THE 'COMMAND CLASS +0B' ROUTINE
1CDE THE 'FETCH A NUMBER' SUBROUTINE
1CEE THE 'STOP' COMMAND ROUTINE
1CF0 THE 'IF' COMMAND ROUTINE
1D03 THE 'FOR' COMMAND ROUTINE
1D86 THE 'LOOK-PROG' SUBROUTINE
1DAB THE 'NEXT' COMMAND ROUTINE
1DDA THE 'NEXT-LOOP' SUBROUTINE
1DEC THE 'READ' COMMAND ROUTINE
1E27 THE 'DATA' COMMAND ROUTINE
1E39 THE 'PASS-BY' SUBROUTINE
1E42 THE 'RESTORE' COMMAND ROUTINE
1E4F THE 'RANDOMIZE' COMMAND ROUTINE
1E5F THE 'CONTINUE' COMMAND ROUTINE
1E67 THE 'GO TO' COMMAND ROUTINE
1E7A THE 'OUT' COMMAND ROUTINE
1E80 THE 'POKE' COMMAND ROUTINE
1E85 THE 'TWO-PARAM' SUBROUTINE
1E94 THE 'FIND INTEGERS' SUBROUTINE
1EA1 THE 'RUN' COMMAND ROUTINE
1EAC THE 'CLEAR' COMMAND ROUTINE
1EED THE 'GO SUB' COMMAND ROUTINE
1F05 THE 'TEST-ROOM' SUBROUTINE
1F1A THE 'FREE MEMORY' SUBROUTINE
1F23 THE 'RETURN' COMMAND ROUTINE
1F3A THE 'PAUSE' COMMAND ROUTINE
1F54 THE 'BREAK-KEY' SUBROUTINE
1F60 THE 'DEF FN' COMMAND ROUTINE
1FC3 THE 'UNSTACK-Z' SUBROUTINE
1FC9 THE 'LPRINT and PRINT' COMMAND ROUTINES
1FDF THE 'PRINT CONTROLLING' SUBROUTINE
1FF5 THE 'PRINT A CARRIAGE RETURN' SUBROUTINE
1FFC THE 'PRINT ITEMS' SUBROUTINE
2045 THE 'END OF PRINTING' SUBROUTINE
204E THE 'PRINT POSITION' SUBROUTINE
2070 THE 'ALTER STREAM' SUBROUTINE
2089 THE 'INPUT' COMMAND ROUTINE
21B9 THE 'IN-ASSIGN' SUBROUTINE
21D6 THE 'IN-CHAN-K' SUBROUTINE
21E1 THE 'COLOUR ITEM' ROUTINES
2294 THE 'BORDER' COMMAND ROUTINE
22AA THE 'PIXEL ADDRESS' SUBROUTINE
22CB THE 'POINT' SUBROUTINE
22DC THE 'PLOT' COMMAND ROUTINE
2307 THE 'STK-TO-BC' SUBROUTINE
2314 THE 'STK-TO-A' SUBROUTINE
2320 THE 'CIRCLE' COMMAND ROUTINE
2382 THE 'DRAW' COMMAND ROUTINE
247D THE 'INITIAL PARAMETERS' SUBROUTINE
24B7 THE 'LINE-DRAWING' SUBROUTINE
24FB THE 'SCANNING' SUBROUTINE
250F THE 'SCANNING QUOTES' SUBROUTINE
2522 THE 'SCANNING TWO CO-ORDINATES' SUBROUTINE
2530 THE 'SYNTAX-Z' SUBROUTINE
2535 THE 'SCANNING SCREEN$' SUBROUTINE
2580 THE 'SCANNING ATTRIBUTES' SUBROUTINE
2596 THE SCANNING FUNCTION TABLE
25AF THE 'SCANNING UNARY PLUS' ROUTINE
25B3 THE 'SCANNING QUOTE' ROUTINE
25E8 THE 'SCANNING BRACKET' ROUTINE
25F5 THE 'SCANNING FN' ROUTINE
25F8 THE 'SCANNING RND' ROUTINE
2627 THE 'SCANNING PI' ROUTINE
2634 THE 'SCANNING INKEY$' ROUTINE
2668 THE 'SCANNING SCREEN$' ROUTINE
2672 THE 'SCANNING ATTR' ROUTINE
267B THE 'SCANNING POINT' ROUTINE
2684 THE 'SCANNING ALPHANUMERIC' ROUTINE
268D THE 'SCANNING DECIMAL' ROUTINE
26C9 THE 'SCANNING VARIABLE' ROUTINE
2795 THE TABLE OF OPERATORS
27B0 THE TABLE OF PRIORITIES
27BD THE 'SCANNING FUNCTION' SUBROUTINE
28AB THE 'FUNCTION SKIPOVER' SUBROUTINE
28B2 THE 'LOOK-VARS' SUBROUTINE
2951 THE 'STACK FUNCTION ARGUMENT' SUBROUTINE
2996 THE 'STK-VAR' SUBROUTINE
2A52 THE 'SLICING' SUBROUTINE
2AB1 THE 'STK-STORE' SUBROUTINE
2ACC THE 'INT-EXP' SUBROUTINE
2AEE THE 'DE,(DE+1)' SUBROUTINE
2AF4 THE 'GET-HL*DE' SUBROUTINE
2AFF THE 'LET' COMMAND ROUTINE
2BF1 THE 'STK-FETCH' SUBROUTINE
2C02 THE 'DIM' COMMAND ROUTINE
2C88 THE 'ALPHANUM' SUBROUTINE
2C8D THE 'ALPHA' SUBROUTINE
2C9B THE 'DECIMAL TO FLOATING POINT' SUBROUTINE
2D1B THE 'NUMERIC' SUBROUTINE
2D22 THE 'STK-DIGIT' SUBROUTINE
2D28 THE 'STACK-A' SUBROUTINE
2D2B THE 'STACK-BC' SUBROUTINE
2D3B THE 'INTEGER TO FLOATING-POINT' SUBROUTINE
2D4F THE 'E-FORMAT TO FLOATING-POINT' SUBROUTINE
2D7F THE 'INT-FETCH' SUBROUTINE
2D8C THE 'POSITIVE-INT-STORE' SUBROUTINE
2D8E THE 'INT-STORE' SUBROUTINE
2DA2 THE 'FLOATING-POINT TO BC' SUBROUTINE
2DC1 THE 'LOG(2^A)' SUBROUTINE
2DD5 THE 'FLOATING-POINT TO A' SUBROUTINE
2DE3 THE 'PRINT A FLOATING-POINT NUMBER' SUBROUTINE
2F8B THE 'CA=10*A+C' SUBROUTINE
2F9B THE 'PREPARE TO ADD' SUBROUTINE
2FBA THE 'FETCH TWO NUMBERS' SUBROUTINE
2FDD THE 'SHIFT ADDEND' SUBROUTINE
3004 THE 'ADD-BACK' SUBROUTINE
300F THE 'SUBTRACTION' OPERATION
3014 THE 'ADDITION' OPERATION
30A9 THE 'HL=HL*DE' SUBROUTINE
30C0 THE 'PREPARE TO MULTIPLY OR DIVIDE' SUBROUTINE
30CA THE 'MULTIPLICATION' OPERATION
31AF THE 'DIVISION' OPERATION
3214 THE 'INTEGER TRUNCATION TOWARDS ZERO' SUBROUTINE
3293 THE 'RE-STACK TWO' SUBROUTINE
3297 THE 'RE-STACK' SUBROUTINE
32C5 THE TABLE OF CONSTANTS
32D7 THE TABLE OF ADDRESSES
335B THE 'CALCULATE' SUBROUTINE
33A2 THE 'SINGLE OPERATION' SUBROUTINE
33A9 THE 'TEST 5-SPACES' SUBROUTINE
33B4 THE 'STACK NUMBER' SUBROUTINE
33C0 THE 'MOVE A FLOATING-POINT NUMBER' SUBROUTINE
33C6 THE 'STACK LITERALS' SUBROUTINE
33F7 THE 'SKIP CONSTANTS' SUBROUTINE
3406 THE 'MEMORY LOCATION' SUBROUTINE
340F THE 'GET FROM MEMORY AREA' SUBROUTINE
341B THE 'STACK A CONSTANT' SUBROUTINE
342D THE 'STORE IN MEMORY AREA' SUBROUTINE
343C THE 'EXCHANGE' SUBROUTINE
3449 THE 'SERIES GENERATOR' SUBROUTINE
346A THE 'ABSOLUTE MAGNITUDE' FUNCTION
346E THE 'UNARY MINUS' OPERATION
3492 THE 'SIGNUM' FUNCTION
34A5 THE 'IN' FUNCTION
34AC THE 'PEEK' FUNCTION
34B3 THE 'USR' FUNCTION
34BC THE 'USR STRING' FUNCTION
34E9 THE 'TEST-ZERO' SUBROUTINE
34F9 THE 'GREATER THAN ZERO' OPERATION
3501 THE 'NOT' FUNCTION
3506 THE 'LESS THAN ZERO' OPERATION
350B THE 'ZERO OR ONE' SUBROUTINE
351B THE 'OR' OPERATION
3524 THE 'NUMBER AND NUMBER' OPERATION
352D THE 'STRING AND NUMBER' OPERATION
353B THE 'COMPARISON' OPERATIONS
359C THE 'STRING CONCATENATION' OPERATION
35BF THE 'STK-PNTRS' SUBROUTINE
35C9 THE 'CHR$' FUNCTION
35DE THE 'VAL' AND 'VAL$' FUNCTIONS
361F THE 'STR$' FUNCTION
3645 THE 'READ-IN' SUBROUTINE
3669 THE 'CODE' FUNCTION
3674 THE 'LEN' FUNCTION
367A THE 'DECREASE THE COUNTER' SUBROUTINE
3686 THE 'JUMP' SUBROUTINE
368F THE 'JUMP ON TRUE' SUBROUTINE
369B THE 'END-CALC' SUBROUTINE
36A0 THE 'MODULUS' SUBROUTINE
36AF THE 'INT' FUNCTION
36C4 THE 'EXPONENTIAL' FUNCTION
3713 THE 'NATURAL LOGARITHM' FUNCTION
3783 THE 'REDUCE ARGUMENT' SUBROUTINE
37AA THE 'COSINE' FUNCTION
37B5 THE 'SINE' FUNCTION
37DA THE 'TAN' FUNCTION
37E2 THE 'ARCTAN' FUNCTION
3833 THE 'ARCSIN' FUNCTION
3843 THE 'ARCCOS' FUNCTION
384A THE 'SQUARE ROOT' FUNCTION
3851 THE 'EXPONENTIATION' OPERATION
3D00 CHARACTER_SET
5C00 KSTATE
5C08 LAST_K
5C09 REPDEL
5C0A REPPER
5C0B DEFADD
5C0D K_DATA
5C0E TVDATA
5C10 STRMS
5C36 CHARS
5C38 RASP
5C39 PIP
5C3A ERR_NR
5C3B FLAGS
5C3C TV_FLAG
5C3D ERR_SP
5C3F LIST_SP
5C41 MODE
5C42 NEWPPC
5C44 NSPPC
5C45 PPC
5C47 SUBPPC
5C48 BORDCR
5C49 E_PPC
5C4B VARS
5C4D DEST
5C4F CHANS
5C51 CURCHL
5C53 PROG
5C55 NXTLIN
5C57 DATADD
5C59 E_LINE
5C5B K_CUR
5C5D CH_ADD
5C5F X_PTR
5C61 WORKSP
5C63 STKBOT
5C65 STKEND
5C67 BREG
5C68 MEM
5C6A FLAGS2
5C6B DF_SZ
5C6C S_TOP
5C6E OLDPPC
5C70 OSPCC
5C71 FLAGX
5C72 STRLEN
5C74 T_ADDR
5C76 SEED
5C78 FRAMES
5C7B UDG
5C7D COORDS
5C7F P_POSN
5C80 PR_CC
5C82 ECHO_E
5C84 DF_CC
5C86 DF_CCL
5C88 S_POSN
5C8A S_POSNL
5C8C SCR_CT
5C8D ATTR_P
5C8E MASK_P
5C8F ATTR_T
5C90 MASK_T
5C91 P_FLAG
5C92 MEMBOT
5CB0 NMIADD
5CB2 RAMTOP
5CB4 P_RAMT
MAP_DATA

sub clean_symbol {
    my ($desc) = @_;
    my $name;
    if ($desc =~ /THE\s+'([^']+)'/) {
        $name = $1;
    } elsif ($desc =~ /THE\s+(.+)/) {
        $name = $1;
    } else {
        $name = $desc;
    }
    $name =~ s/[^A-Za-z0-9]/_/g;
    $name =~ s/_+/_/g;
    $name =~ s/^_|_$//g;
    return uc($name);
}

open(my $fh, '>', $output) or die "Cannot write $output: $!\n";
print $fh "; ZX Spectrum 48K ROM Symbol Map\n";
print $fh "; Generated from https://skoolkid.github.io/rom/maps/all.html\n";
print $fh ";\n";

my $count = 0;
for my $line (@raw) {
    next unless $line =~ /^([0-9A-Fa-f]{4})\s+(.+)$/;
    my ($addr, $desc) = (uc($1), $2);
    my $symbol = clean_symbol($desc);
    next unless $symbol;
    printf $fh "%-40s = \$%s\n", $symbol, $addr;
    $count++;
}
close($fh);
print "Generated $count symbols to $output\n";
PERL_SCRIPT
