#include "peripheral/i2c.h"
#include "core/log.h"
#include "core/saveable.h"

// Local I2C logger — created on first use, follows the same pattern as Log::make()
namespace {
    std::shared_ptr<spdlog::logger>& i2c_log() {
        static auto logger = [] {
            auto existing = spdlog::get("i2c");
            if (existing) return existing;
            auto l = spdlog::stderr_color_mt("i2c");
            l->set_pattern("[%H:%M:%S.%e] [%n] [%^%l%$] %v");
            return l;
        }();
        return logger;
    }
}

// ─── I2cRtc ──────────────────────────────────────────────────────────

I2cRtc::I2cRtc() {
    snapshot_time();
}

void I2cRtc::reset() {
    reg_ptr_ = 0;
    addr_set_ = false;
    osc_halt_ = false;
    mode_12h_ = false;
    use_real_time_ = true;
    regs_.fill(0);
}

void I2cRtc::start() {
    addr_set_ = false;
    snapshot_time();
}

uint8_t I2cRtc::transfer(uint8_t data, bool is_read) {
    if (is_read) {
        // Read: return register at current pointer, auto-increment
        uint8_t val = regs_[reg_ptr_];
        i2c_log()->debug("RTC read reg {:#04x} = {:#04x}", reg_ptr_, val);
        reg_ptr_ = (reg_ptr_ + 1) & 0x3F;     // DS1307: wrap 0x3F → 0x00
        return val;
    }

    // Write path. First write-byte in the transaction sets the
    // register pointer; subsequent bytes are data writes that
    // auto-increment the pointer (DS1307 datasheet §Address
    // Autoincrement).
    if (!addr_set_) {
        reg_ptr_ = data & 0x3F;
        addr_set_ = true;
        i2c_log()->debug("RTC set register pointer = {:#04x}", reg_ptr_);
        return 0; // ACK
    }

    // Data byte — apply per-register semantics.
    switch (reg_ptr_) {
    case 0x00:
        // Seconds: bits 6:0 = BCD seconds; bit 7 = CH (Clock Halt).
        regs_[0x00] = data & 0x7F;
        osc_halt_   = (data & 0x80) != 0;
        if (osc_halt_) {
            regs_[0x00] |= 0x80;             // persist CH bit visibly
        }
        break;
    case 0x02:
        // Hours: bit 6 = 12h mode; bit 5 = AM/PM (when 12h); bits 4:0 = BCD.
        // Store verbatim — both the mode bit and the AM/PM flag must
        // round-trip exactly.
        regs_[0x02] = data & 0x7F;           // bit 7 reserved, always 0
        mode_12h_   = (data & 0x40) != 0;
        break;
    default:
        // reg 0x01 (minutes), 0x03-0x06 (wday/date/month/year),
        // 0x07 (control), 0x08-0x3F (NVRAM) — store verbatim.
        regs_[reg_ptr_] = data;
        break;
    }
    i2c_log()->debug("RTC write reg {:#04x} = {:#04x}", reg_ptr_, data);
    reg_ptr_ = (reg_ptr_ + 1) & 0x3F;
    return 0; // ACK
}

void I2cRtc::stop() {
    // Nothing to do
}

uint8_t I2cRtc::to_bcd(int val) {
    return static_cast<uint8_t>(((val / 10) << 4) | (val % 10));
}

void I2cRtc::snapshot_time() {
    // Oscillator halted or deterministic mode → leave regs_[0..6] alone.
    // DS1307 datasheet §Clock Halt: when CH=1 the on-chip oscillator
    // is stopped and the time registers do not advance. Wave-E tests
    // also use `use_real_time_=false` to freeze the snapshot so poked
    // BCD values round-trip verbatim.
    if (osc_halt_ || !use_real_time_) {
        return;
    }

    std::time_t now = std::time(nullptr);
    std::tm* t = std::localtime(&now);
    if (!t) return;

    regs_[0] = to_bcd(t->tm_sec);             // 0x00: seconds (BCD, bit 7 = CH = 0)
    regs_[1] = to_bcd(t->tm_min);             // 0x01: minutes
    regs_[2] = to_bcd(t->tm_hour);            // 0x02: hours (24h mode, bit 6 = 0)
    regs_[3] = to_bcd(t->tm_wday + 1);        // 0x03: day of week (1-7)
    regs_[4] = to_bcd(t->tm_mday);            // 0x04: date
    regs_[5] = to_bcd(t->tm_mon + 1);         // 0x05: month (1-12)
    regs_[6] = to_bcd(t->tm_year % 100);      // 0x06: year (00-99)
    // regs_[0x07] (control) and regs_[0x08..0x3F] (NVRAM) are never
    // touched by the host-time snapshot.
}

// ─── I2cController ───────────────────────────────────────────────────

I2cController::I2cController() {
    reset();
}

void I2cController::reset() {
    scl_ = 1;
    sda_out_ = 1;
    sda_in_ = 1;
    prev_scl_ = 1;
    prev_sda_ = 1;
    // pi_i2c1_scl_ / pi_i2c1_sda_ are hardware inputs — default released (1),
    // not reset by the internal controller. A real Pi would drive them low
    // when asserting.
    pi_i2c1_scl_ = true;
    pi_i2c1_sda_ = true;
    state_ = State::IDLE;
    bit_count_ = 0;
    shift_reg_ = 0;
    device_addr_ = 0;
    is_read_ = false;
    read_data_ = 0xFF;
    active_device_ = nullptr;
}

void I2cController::write_scl(uint8_t val) {
    prev_scl_ = scl_;
    scl_ = val & 0x01;

    // START/STOP are SDA transitions while SCL is high — they are only
    // generated by write_sda(). Calling detect_start_stop() here against a
    // stale prev_sda_ caused a spurious STOP on the first bit of every
    // i2c_send_byte (reset state to IDLE before the slave could sample).

    // Detect SCL edges
    if (prev_scl_ == 0 && scl_ == 1) {
        on_scl_rising();
    } else if (prev_scl_ == 1 && scl_ == 0) {
        on_scl_falling();
    }
}

void I2cController::write_sda(uint8_t val) {
    prev_sda_ = sda_out_;
    sda_out_ = val & 0x01;

    // Check for START/STOP (SDA transitions while SCL high)
    detect_start_stop();
}

uint8_t I2cController::read_scl() const {
    // Upper 7 bits read as 1 (pulled high), bit 0 is SCL state.
    // zxnext.vhd:3259: port_103b_dat <= "1111111" & (i_I2C_SCL_n and pi_i2c1_scl);
    // Our scl_ mirrors i_I2C_SCL_n (the local master drives it). pi_i2c1_scl_
    // defaults to 1 (released) — AND-gate is a no-op until a test drives low.
    return 0xFE | (scl_ & pi_i2c1_scl_);
}

uint8_t I2cController::read_sda() const {
    // Upper 7 bits read as 1 (pulled high), bit 0 is SDA input.
    // zxnext.vhd:3266: port_113b_dat <= "1111111" & (i_I2C_SDA_n and pi_i2c1_sda);
    // SDA is the wired-AND of sda_out_, the device-driven sda_in_, and the
    // Raspberry Pi bridge sda (open-drain on all three sides).
    return 0xFE | (sda_out_ & sda_in_ & pi_i2c1_sda_);
}

void I2cController::attach_device(uint8_t address, I2cDevice* device) {
    devices_[address & 0x7F] = device;
    i2c_log()->info("I2C device attached at address {:#04x}", address & 0x7F);
}

void I2cController::detect_start_stop() {
    // START: SDA falls while SCL is high
    if (scl_ == 1 && prev_sda_ == 1 && sda_out_ == 0) {
        i2c_log()->debug("I2C START condition");
        state_ = State::ADDRESS;
        bit_count_ = 0;
        shift_reg_ = 0;
        active_device_ = nullptr;
    }

    // STOP: SDA rises while SCL is high
    if (scl_ == 1 && prev_sda_ == 0 && sda_out_ == 1) {
        i2c_log()->debug("I2C STOP condition");
        if (active_device_) {
            active_device_->stop();
        }
        state_ = State::IDLE;
        active_device_ = nullptr;
        sda_in_ = 1; // release SDA
    }
}

void I2cController::on_scl_rising() {
    // Data is sampled on SCL rising edge
    switch (state_) {
    case State::IDLE:
        break;

    case State::ADDRESS:
    case State::DATA:
        // Sample SDA into shift register (MSB first)
        shift_reg_ = (shift_reg_ << 1) | sda_out_;
        bit_count_++;

        if (bit_count_ >= 8) {
            if (state_ == State::ADDRESS) {
                device_addr_ = (shift_reg_ >> 1) & 0x7F;
                is_read_ = (shift_reg_ & 0x01) != 0;
                i2c_log()->debug("I2C address={:#04x} R/W={}", device_addr_, is_read_ ? "R" : "W");

                // Look up device
                auto it = devices_.find(device_addr_);
                if (it != devices_.end()) {
                    active_device_ = it->second;
                    active_device_->start();
                    // If read, pre-load first data byte
                    if (is_read_) {
                        read_data_ = active_device_->transfer(0, true);
                    }
                } else {
                    active_device_ = nullptr;
                    i2c_log()->debug("I2C no device at address {:#04x}", device_addr_);
                }
                state_ = State::ACK_ADDR;
            } else {
                // DATA phase (write direction)
                if (active_device_ && !is_read_) {
                    active_device_->transfer(shift_reg_, false);
                }
                state_ = State::ACK_DATA;
            }
        }
        break;

    case State::ACK_ADDR:
        // ACK bit is being sampled — we set sda_in_ on falling edge
        break;

    case State::ACK_DATA:
        // ACK bit is being sampled
        if (is_read_) {
            // Master drives ACK/NACK for reads; sample it
            uint8_t master_ack = sda_out_;
            if (master_ack == 1) {
                // NACK — master doesn't want more data
                i2c_log()->debug("I2C master NACK (read done)");
            }
        }
        break;
    }
}

void I2cController::on_scl_falling() {
    // Output data on SCL falling edge (device drives SDA for reads/ACKs)
    switch (state_) {
    case State::IDLE:
        break;

    case State::ADDRESS:
    case State::DATA:
        if (is_read_ && state_ == State::DATA) {
            // Device drives SDA with current bit of read data
            uint8_t bit_idx = 7 - bit_count_;
            sda_in_ = (read_data_ >> bit_idx) & 0x01;
        } else {
            sda_in_ = 1; // release SDA for master to drive
        }
        break;

    case State::ACK_ADDR:
        // The ACK phase spans a full clock cycle.  The first falling edge
        // (after the 8th data bit rising) drives the ACK/NACK.  The second
        // falling edge (after the master's ACK clock rising) transitions to
        // DATA.  We use bit_count_ != 0 to distinguish: it is 8 on the
        // first falling (set by the 8th rising), reset to 0 afterward.
        if (bit_count_ != 0) {
            // First falling: drive ACK
            if (active_device_) {
                sda_in_ = 0; // ACK
                i2c_log()->debug("I2C ACK address");
            } else {
                sda_in_ = 1; // NACK — no device
                i2c_log()->debug("I2C NACK address (no device)");
            }
            bit_count_ = 0;
        } else {
            // Second falling: transition to DATA phase
            state_ = State::DATA;
            shift_reg_ = 0;
            // For reads, place MSB on SDA so the master can sample it
            // on the first data clock rising edge.
            if (is_read_ && active_device_) {
                sda_in_ = (read_data_ >> 7) & 0x01;
            }
        }
        break;

    case State::ACK_DATA:
        if (bit_count_ != 0) {
            // First falling: drive ACK / release for master ACK
            if (is_read_) {
                sda_in_ = 1; // release for master ACK/NACK
            } else {
                sda_in_ = (active_device_) ? 0 : 1;
                i2c_log()->debug("I2C {} data write", active_device_ ? "ACK" : "NACK");
            }
            bit_count_ = 0;
        } else {
            // Second falling: sample master ACK for reads, load next byte
            if (is_read_ && active_device_) {
                if (sda_out_ == 0) {
                    // Master ACKed — load next byte
                    read_data_ = active_device_->transfer(0, true);
                }
                // Place MSB of next byte (or keep last if NACKed)
                sda_in_ = (read_data_ >> 7) & 0x01;
            }
            state_ = State::DATA;
            shift_reg_ = 0;
        }
        break;
    }
}

void I2cRtc::save_state(StateWriter& w) const
{
    w.write_u8(reg_ptr_);
    w.write_bool(addr_set_);
    // Phase-1 widened regs_ 8→64 per DS1307 NVRAM; Wave E added CH / 12h /
    // use_real_time flags. Rewind buffer is in-process only (plan R3), so a
    // straight size/field bump is safe. Order: regs_ first, then flag triple.
    w.write_bytes(regs_.data(), regs_.size());
    w.write_bool(osc_halt_);
    w.write_bool(mode_12h_);
    w.write_bool(use_real_time_);
}

void I2cRtc::load_state(StateReader& r)
{
    // Must mirror save_state field order exactly: reg_ptr, addr_set, regs_,
    // then osc_halt / mode_12h / use_real_time flag triple.
    reg_ptr_       = r.read_u8();
    addr_set_      = r.read_bool();
    r.read_bytes(regs_.data(), regs_.size());
    osc_halt_      = r.read_bool();
    mode_12h_      = r.read_bool();
    use_real_time_ = r.read_bool();
}

void I2cController::save_state(StateWriter& w) const
{
    w.write_u8(scl_);
    w.write_u8(sda_out_);
    w.write_u8(sda_in_);
    w.write_u8(prev_scl_);
    w.write_u8(prev_sda_);
    w.write_u8(static_cast<uint8_t>(state_));
    w.write_u8(bit_count_);
    w.write_u8(shift_reg_);
    w.write_u8(device_addr_);
    w.write_bool(is_read_);
    w.write_u8(read_data_);
    // Phase-1: pi_i2c1 inputs — saved so rewind replays them correctly.
    w.write_bool(pi_i2c1_scl_);
    w.write_bool(pi_i2c1_sda_);
}

void I2cController::load_state(StateReader& r)
{
    scl_         = r.read_u8();
    sda_out_     = r.read_u8();
    sda_in_      = r.read_u8();
    prev_scl_    = r.read_u8();
    prev_sda_    = r.read_u8();
    state_       = static_cast<State>(r.read_u8());
    bit_count_   = r.read_u8();
    shift_reg_   = r.read_u8();
    device_addr_ = r.read_u8();
    is_read_     = r.read_bool();
    read_data_   = r.read_u8();
    pi_i2c1_scl_ = r.read_bool();
    pi_i2c1_sda_ = r.read_bool();
}
